### ISSUE TITLE
Script Active bug

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#513] opened 2015-10-09 11:52 UTC
This problem happens in mGBA and VBA-Next.
When a script is active, and I drag and drop the same file on the console (in the expectation it would close the script), the script will keep running. When dragging and dropping the file again, a 2nd instance of the script will start running. Please refer to "Script active problem" heading in this post:
http://tasvideos.org/forum/viewtopic.php?p=419941#419941

**Comment by zeromus** [comment] 2015-10-17 23:25
Here's some commit messages from the past

1. If User Opens A Script That Is Currently On The Session, It Will Toggle It On. (rolanmen1)
2. Lua Console - When opening a duplicate lua script, don't turn script on if the disable lua script on load option is checked (adelikat)
3. Lua Console - when removing a script, remove its registered function.  Currently however, this behavior will only happen if the script is currently running.  If you disable it and then remove it, the functions remain. (adelikat)

So the question is, what happens when you drag a lua script onto the console that already exists? 
The answer is: WHO KNOWS!? ITS SO COMPLICATED.

I think you and me both believe it should be exactly identical to deleting the lua script and then re-adding it. Events should be removed, and then if the script is supposed to be run (due to that option) then it will be re-run and the events re-added.

I disagree with commit#3 entirely. Maybe it's powerful, but it's confusing as hell. I think we should add a menu button or something instead which lets you delete it while keeping events, since in my book, that's an advanced move. Practically everyone is going to want all traces of a script eradicated when they're removing a script.

**Comment by vadosnaprimer** [comment] 2016-01-29 13:23
I added 2 features for you to not need drag-n-drop for reloading. First, if "return all if none selected" is on, pressing the refresh button updates the scripts you don't need to select every time. And to avoid registering duplicate functions, there's an option to "remove registered functions on toggle" (which is basically what refresh does). So you edit, press the button, voila, it updated, and no garbage is registered. The logical karate that is there in drag-n-drop won't get called, and we don't need to ill-fix it.

**Comment by vadosnaprimer** [comment] 2016-03-04 19:03
With the newest feature of autoreloading, all of this might become irrelevant btw.

**Comment by YoshiRulz** [comment] 2019-03-01 14:30
Current behaviour when dragging file into Lua Console while said file is loaded and running is:
1. existing copy stops running (my script was `event.onsavestate` followed by the simplest `emu.frameadvance` loop)
2. no new copy is added
3. previously added event callbacks are not duplicated (option `Remove Registered Functions on Toggle` was checked), triggering the event only runs the function once as expected

Closing as I could not reproduce on 2.3.1.

**Closed by YoshiRulz** 2019-03-01 14:30 UTC
Labels: App-EmuHawk, Topic-Lua
