### ISSUE TITLE
add emu.pause() and movie.load([string filename = ])

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2099] opened 2020-06-05 08:59 UTC
FCEUX has an emu.pause() function, and I think that BizHawk should too.

It also needs to get a function for opening/creating a movie file.

**Comment by YoshiRulz** [comment] 2020-06-05 10:38
1. `client.ispaused`/`client.pause`/`client.unpause`
2. duplicate of #384

**Closed by YoshiRulz** 2020-06-05 10:38 UTC
