### ISSUE TITLE
Genesis Plus GX Audio Issues

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2633] opened 2021-02-21 12:01 UTC
If the region is set to PAL (Europe) while you are using BizHawk 2.6, the audio suddenly rises in pitch while maintaining speed.
This did not happen in previous releases, I don't know why this began happening. Using Audio Throttle in Speed/Skip will prevent this.

**Comment by nattthebear** [comment] 2021-02-21 14:14
Duplicate of #2580

**Closed by nattthebear** 2021-02-21 14:14 UTC
