### ISSUE TITLE
TASstudio: Error

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#577] opened 2016-02-19 21:42 UTC
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Value of '110' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
> Parameter name: Value
>    at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
>    at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
>    at BizHawk.Client.EmuHawk.TAStudio.<InitializeSeekWorker>b__b(Object s, ProgressChangedEventArgs e)
>    at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
>    at System.ComponentModel.BackgroundWorker.ProgressReporter(Object arg)

I got this error by messing with TASstudio.

Didn't pay attention with what I did, but I did these durin my session:
-Save Branch, Load branch
-Do a Movie
-Edit Branch text
-Saved one branch without the lag counter, then saved a second branch with the lag counter(and modifying the movie)

If I get a better way to repro, I'll post.

**Comment by zeromus** [comment] 2016-03-04 08:00
Let me consult my magic ball to find which bizhawk version youre running

**Comment by Niamek** [comment] 2016-03-04 12:26
I'm running the last release. But I can't seem to repro it. I was considering closing this and my other report since I felt I've should've at least find a repro steps before reporting it. Sorry again.

**Comment by vadosnaprimer** [comment] 2016-03-04 13:09
This actually used to happen when scrolling up with right button held, but I fixed it some time. Not sure if it's been released since then or not.

**Comment by Niamek** [comment] 2016-03-04 19:19
I do recall that one of those 2 (I think it's that one actually) occured after scrolling(I was indeed scrolling, but downward and not upward?), but I didn't think it was the scrolling the problem since I couldn't repro anything with scrolling.

**Comment by vadosnaprimer** [comment] 2016-03-24 12:47
Closing for now, if you reproduce it, tell us.

**Closed by vadosnaprimer** 2016-03-24 12:47 UTC
