### ISSUE TITLE
Duck Tales 2 bug

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#1055] opened 2017-11-16 15:43 UTC
Something mess with objects (in this case - 2 chests), and look on the protagonist's position. Core - QuickNes , on NesHawk its alright.

DuckTales 2, Disney's
SHA1:76093EA07A16FDAA8AA58730FD29B4977A264B5E
MD5:EE092394B1E64B8BEE7CA54C3DC7FAAD

Bizhawk - NesHawk core

![duck tales 2 u -0](https://user-images.githubusercontent.com/28905475/32900076-45903f3c-caf5-11e7-8954-4f71e34679a3.png)

Bizhawk developer with latest commit 213c818  / Bizhawk 2.2 (QuickNes core)

![ducktales 2 disney s 2017-11-16 17 39 46](https://user-images.githubusercontent.com/28905475/32900122-64eade46-caf5-11e7-91f6-86cc86f6dc9e.png)

**Comment by zeromus** [comment] 2017-11-16 16:31
probably irq timing bug, not likely ever to get fixed in quicknes, by design. about all we can ever do there is add new mappers

**Closed by zeromus** 2017-11-16 16:31 UTC
