### ISSUE TITLE
Saturnus can lose input when the "U+D/L+R" setting is set to "Allow" in the controller option

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1194] opened 2018-05-09 03:41 UTC
When utilizing the U+D/L+R input option with the saturn core, if you press both inputs at the same time, games detect the gamepad as no longer connected. Once the button combo is released, games recognize the controller again.

As far as I can tell, this doesn't seem intended but I'm not sure if this is how an actual Saturn handles things (couldn't find any info online)

**Comment by NarryG** [comment] 2018-05-09 03:44
Fxed the description (posted too early)

**Comment by vadosnaprimer** [comment] 2018-05-09 05:17
Try in mednafen?

**Comment by NarryG** [comment] 2018-05-09 05:49
The issue does not appear to occur in the latest Mednafen stable. In the case of Doom, holding both left and right brings the movement to a stop. Releasing either one results in you starting to move in the direction of the one still held down. 
Within Bizhawk (with the setting on allow) the game displays a message that the joypad had been disconnected until you release one of the buttons

I'm unsure if stock Mednafen uses a true "allow both" input method though.
Doing a quick check with Zelda II in Mednafen, it doesn't appear to do a true "allow both.
Doing some quick googling, I'm finding a post about how to allow multiple directions at once on PSX you need to use the "Dance Pad" input method.

**Comment by nattthebear** [comment] 2018-05-11 21:00
This sounds weird enough that it might actually be real console behavior.  Maybe the electrical configuration of no device connected gives register values that match the configuration of L+R allowed.  Maybe games check for L+R in software, and since "no real controller could possibly produce it", treat it as a controller disconnected event.

**Comment by nattthebear** [comment] 2018-05-11 21:37
Spoke with an expert in mednafen irc about this.  When directions are held simultaneously on the plain digital pad, the SMPC's controller id calculations get screwed up by the data and effects like this can happen.

Try the 3d pad if you want to hold U+D or L+R at the same time.  Or, if you're making a TAS, this broken behavior might actually lead to a useful glitch.

Closing because working as intended.

**Closed by nattthebear** 2018-05-11 21:37 UTC
