### ISSUE TITLE
GBHawk: Totsugeki! Ponkotsu Tank desynchronization

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2406] opened 2020-09-16 07:21 UTC
I recorded an input movie where I play through the arena mode of Totsugeki! Ponkotsu Tank (Japanese version of Trax) where I play through all 12 arenas and then lose on purpose. The input movie instead desynchs in random parts.

[Totsugeki! Ponkotsu Tank - arena mode.zip](https://github.com/TASVideos/BizHawk/files/5230337/Totsugeki.Ponkotsu.Tank.-.arena.mode.zip)

**Comment by alyosha-tas** [comment] 2020-09-17 00:56
I found a variable missing from the savestate that could be the cause here. please re-test in dev build.

**Comment by adelikat** [comment] 2020-10-04 22:14
No response from reporter, marking this as fixed

**Comment by Reinc01** [comment] 2020-10-05 02:12
No response because I don't have the dev version, so I can't check if the fix worked or not.

**Comment by zeromus** [comment] 2020-10-05 02:57
The typical response to "Found your bug probably. Please test it." in cases where you don't know how test it is "how do I test it", not "<silence>"

**Comment by YoshiRulz** [comment] 2020-10-05 03:00
Instructions for getting a dev build are [in the readme](https://github.com/TASVideos/BizHawk#development-builds).

**Comment by Reinc01** [comment] 2020-10-05 05:08
It's not a "probably a bug", it's a bug. I tried playing the same input movie in the lastest dev build, and the desyncs still happen.

**Comment by zeromus** [comment] 2020-10-05 05:14
Good thing I didn't say it was probably a bug but rather that it was a bug that had probably been found. After alyosha's fix your movie is not guaranteed to sync. In fact it's likely that it won't. When a bug like that is fixed you need to repair the movie. After it's repaired, it should be stable.

**Comment by RetroEdit** [comment] 2020-10-05 13:17
To clarify, zeromus is saying you need to recreate the movie in the dev build to show that there's actually inconsistent savestates in the dev build.

Just playing back the original movie shows that the one particular movie doesn't work, it doesn't mean there's a desync with savestates necessarily unless you specifically show that.

Or at least, I assume you used savestates in the process of creating the original movie?

**Comment by Reinc01** [comment] 2020-10-05 14:09
The arena mode movie starts with power-on.

**Comment by RetroEdit** [comment] 2020-10-05 14:19
Yeah, then merely playing back the old movie just shows that the old movie desyncs, not that a newly-created movie would still desync (because the probable cause of the desync was savestates, not emulation).

**Comment by Reinc01** [comment] 2020-10-08 03:20
I've recorded a new movie with the most recent dev build, and desynchs still happen in the arena mode.

**Comment by zeromus** [comment] 2020-10-08 03:43
I just did a quick run with the tastudio integrity checker and found a discrepancy in the very 0th frame at what seems to be master_audio_clock in the audio component. I don't think that's a real issue but really it probably has more to do with the integrity checker trying to turbo and the audio synthesis getting skipped, but i figured I'd write it here anyway.

**Comment by alyosha-tas** [comment] 2020-10-08 16:32
Weird, I'll look into it.

**Comment by alyosha-tas** [comment] 2020-10-09 00:25
@Reinc01 Does the US version also desync? can you provide more exact reproduction steps?

**Comment by Reinc01** [comment] 2020-10-09 02:17
I did not check the US version. You can see the desynchronization happening in the input movie that attached to my first message. Reproduction steps:
1. Record movie from power-on.
2. Play arena mode.
3. Play through at least one arena (while using save states)
4. Play movie, see desynch.

**Comment by alyosha-tas** [comment] 2020-10-09 20:49
Hmmm,

Does it desync if you try to do the same thing in Gambatte?

Also while I'm thinking of it can you please re-test this issue you reported a while ago:

_Litti's Summer Sports keeps crashing/freezing at the beginning of the first weightlifting event._

**Comment by Reinc01** [comment] 2020-10-10 03:39
There is no desynchronization when I record in Gambatte. Litti's Summer Sports still crashes at the same spot.

**Comment by alyosha-tas** [comment] 2021-05-27 13:24
autofire was used in the .bk2 here, so I'm closing this one too.

@Reinc01 please retest in 2.6.2

**Closed by alyosha-tas** 2021-05-27 13:24 UTC
Labels: Core: GBHawk, Repro: Affects 2.5
