### ISSUE TITLE
SNES Faust core: Trials of Mana crash

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2408] opened 2020-09-17 11:15 UTC
I can't get the Faust core to open my Trials of Mana ROM. When I try, Bizhawk closes. This did not happen with Bizhawk 2.4.2 where I used the BSNES core.

**Comment by zeromus** [comment] 2020-09-17 11:17
so use the bsnes core in whatever version of bizhawk you're using now.

**Comment by nattthebear** [comment] 2020-09-17 11:44
Duplicate of https://github.com/TASVideos/BizHawk/issues/2394

**Closed by nattthebear** 2020-09-17 11:44 UTC
