### ISSUE TITLE
Bizhawk won't open

### ISSUE THREAD

**Issue by Stingerman06** [TASVideos/BizHawk#555] opened 2016-01-16 17:13 UTC
Computer OS: Windows 7 32x
Bizhawk Version: 1.11.4
Pre-Requisites Version: 1.2

When I grabbed Bizhawk the first time, usually I have no issues when I install the Pre-Requisites and then open Bizhawk. Everything opened up and worked normally 100% fine. Any version I could find. Usually anyway.

I had a issue later after the installation of Bizhawk and had to restore back to a point in my computer with system restore. The restore point was in fact after I installed Bizhawk and the installer to be able to run it. Now I attempt to run the emulator and it won't run. In the task manager, it immediately closes. So I removed both Bizhawk and the Pre-Requisites installer, re-downloaded them from TASvideos, then reinstalled the Pre-Requisites. Started fresh again.

Now when I attempt to open Bizhawk, in the Task manager, Bizhawk.exe is shown(I don't open Discohawk usually ever) without any usage. The memory used however is quite high, about 40.9 M for that process alone. Also when opening Bizhawk, cgc.exe runs but doesn't show anything extra. I know what that does, but it didn't do anything when it ran. Nothing else happens, the processes themselves don't close on their own(I have to manually end the tasks), no windows open up and no extra files are added in the Bizhawk directory.

This type of issue has been occurring on every version I can get a hold of. Every time. Is there anything I need to mess with? I know my way around the computer very well, but this is a bothersome issue I need solved. I miss TASing so much. I would assume I would need to remove the installed files needed to run Bizhawk since they might be corrupted, but I want to play this safe.

Is there any way to make a Pre-Requisite checker to check for bad installations that came with the Pre-Requisite installers?

**Comment by zeromus** [comment] 2016-01-18 05:32
Clearly the problem isn't with bizhawk versions, but with your broken computer whose restoration process failed, apparently. 

Yes, there's a way to make the pre-requisite installer check for bad installations, if we know how it's gone bad, which we don't for you.

All I can do is remote control debug your broken system, if you wish. I might get useful information from that, or I might not, and either way, I cant promise I can fix it.

**Comment by Stingerman06** [comment] 2016-01-18 06:04
Ok. I'm ok with remote assistance, since the computer is somewhat hardly touched or personalized. Would be a great help for me. Although I don't know what server or channel for IRC to get on. Once I know that, I'll jump on to get the issue fixed.

**Comment by zeromus** [comment] 2016-01-18 07:55
https://webchat.freenode.net/
#bizhawk

**Comment by Stingerman06** [comment] 2016-01-18 16:38
Excellent. I'll be on there using the same username I use here. Thanks again.

**Comment by zeromus** [comment] 2016-01-20 23:04
User's windows installation is hosed. Console processes can't run; cgc.exe was freezing consequently. We won't be adding a workaround for this insane problem i've never seen before in my life.

**Closed by zeromus** 2016-01-20 23:04 UTC
