### ISSUE TITLE
Movie "record from now" desyncs with savestates

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2438] opened 2020-10-03 04:26 UTC
BizHawk 2.5.1 Stable
I recorded final boss fighting bk2 movie of _Hokuto no Ken_, and replay it, it desyncs. I tried several times, it always desync.
This is bk2 movie:
[Hokuto no Ken Final Boss Fighting.zip](https://github.com/TASVideos/BizHawk/files/5321082/Hokuto.no.Ken.Final.Boss.Fighting.zip)
ROM used _Hokuto no Ken (J) [!].nes_ in _GoodNES 3.23b_ pack.

**Comment by adelikat** [comment] 2020-10-05 16:31
I did some digging on this and this ROM maps to the CNROM mapper.  I double checked and we are saving all the mapper variables we need to do, so it isn't a simple case of missing a value.

a .bk2 that is already in a desynced state, there isn't really anything we can do.  Can you reproduce this in a way that involves creating a movie that consistently produces this problem?

**Comment by Yave-Yu** [comment] 2020-10-06 00:08
Well, try to record "now" movie from here?
[Hokuto no Ken.NesHawk.QuickSave1.State.zip](https://github.com/TASVideos/BizHawk/files/5330683/Hokuto.no.Ken.NesHawk.QuickSave1.State.zip)

**Comment by Yave-Yu** [comment] 2020-12-15 00:39
2.5.2 still have this problem... now I need 2.4.2 version, that works fine.

**Comment by Yave-Yu** [comment] 2020-12-28 00:51
Seems 2020-12-26-024447-#ce0ccd0cfa413190ff65dd5d9c416db2fba3993f has fixed this issue, nice.

**Comment by YoshiRulz** [comment] 2020-12-28 01:15
Was probably 7865fe298

**Comment by Yave-Yu** [comment] 2020-12-28 01:53
Well, seems the issue happened again.
This time, I played _Wolverine_, recorded final boss battle, then replay it, desynced.
So I post the savestate here, you can record "now" from here.
[Wolverine.NesHawk.QuickSave1.State.zip](https://github.com/TASVideos/BizHawk/files/5745609/Wolverine.NesHawk.QuickSave1.State.zip)

ROM: Wolverine (U) [!].nes
SHA1: 72279226339938A684292BF17BBAEEF78B67C788

**Comment by adelikat** [comment] 2020-12-28 01:56
Did it happen on latest master? or again on the latest release?

**Comment by Yave-Yu** [comment] 2020-12-28 02:09
> Did it happen on latest master? or again on the latest release?

Well, I tested again, and I finally find exactly reason: **Input Method**
If I use DirectInput+XInput, it works fine; if OpenTK, it will desync (appearence the issue happens in recording).

**Comment by Yave-Yu** [comment] 2021-01-19 11:48
I'm sorry I not describe it clearly before. "Record from Now" desyncs when **use savestates**, and not always happen. Also this issue happens on entire BizHawk, not just NESHawk core. Affects 2.5 not 2.5.1.
2.6 stable came out, I will try one more time.

ROM: Wolverine (U) [!].nes
Savestate: [Wolverine.NesHawk.QuickSave1.State.zip](https://github.com/TASVideos/BizHawk/files/5745609/Wolverine.NesHawk.QuickSave1.State.zip)

In recording, I blowed the final boss down! (at 710-frame)
![Recording](https://user-images.githubusercontent.com/54294476/105030600-fc51b080-5a8e-11eb-8a39-1d9ddd8cfded.png)

OK, stop recording and replay it, 57 rerecord counts.
Final boss won't be blowed down at 710-frame...
![Replay](https://user-images.githubusercontent.com/54294476/105030702-22775080-5a8f-11eb-9a1c-92170bb87391.png)

**Comment by Yave-Yu** [comment] 2021-01-19 15:59
I'm sorry I'm not describe it clearly before.
Record from now desyncs **with savestates**, and not always happen.
Please recheck it.

**Comment by adelikat** [comment] 2021-01-19 16:00
Have you tried with BIzHawk 2.6?

**Comment by Yave-Yu** [comment] 2021-01-20 02:39
OK, I now try 2.6 stable, choose _Wolverine_ and beat final boss again.
ROM: Wolverine (U) [!].nes
[Wolverine.NesHawk.QuickSave1.State.zip](https://github.com/TASVideos/BizHawk/files/5745609/Wolverine.NesHawk.QuickSave1.State.zip)

In recording, I blowed the final boss down! (F1100)
![Recording](https://user-images.githubusercontent.com/54294476/105119443-4f694900-5b0b-11eb-95b8-945f884928f1.png)

OK, stop recording and replay it, 54 rerecord counts.
No, at F700~ this guy just hit nothing and the final boss won't be blowed down.
![Playing](https://user-images.githubusercontent.com/54294476/105119486-627c1900-5b0b-11eb-8991-86a7c3e32570.png)

Seems the issue still present.

**Comment by alyosha-tas** [comment] 2021-06-01 19:09
Initial movie used autofire, but this issue seems to have evolved considerably since it was posted.

@Yave-Yu please re-test in dev build or 2.6.2

**Comment by zeromus** [comment] 2021-06-01 19:16
I'm hoping whatever this is is what's breaking record from now on psx....

**Comment by Yave-Yu** [comment] 2021-06-07 04:47
2.6.2 Stable
Seems my old _Wolverine_ savestate and movie are no longer usable, so I choose another game _Bio Miracle Bokutte Upa_.
Record from now, from stage 1-1's beginning (when graphics were complete loaded).
![1](https://user-images.githubusercontent.com/54294476/120960273-0fd78c80-c78e-11eb-9a33-19622e76afc3.png)
I get hurt and die then load state continually, and finally went here at F4465.
![2](https://user-images.githubusercontent.com/54294476/120960419-5f1dbd00-c78e-11eb-95ea-2dfd7e6af47b.png)
Rerecord count: 58, now replay it...
![3](https://user-images.githubusercontent.com/54294476/120960441-6d6bd900-c78e-11eb-9265-04893a250473.png)
Same result! Seems this issue fixed?

**Comment by alyosha-tas** [comment] 2021-06-07 13:04
Ok thanks for testing. I had done some 'record from now' testing myself and didn't notice any issues.

I think PSX has it's own unrelated issues.

closing.

**Closed by alyosha-tas** 2021-06-07 13:04 UTC
Labels: Core: NesHawk, Repro: Affects 2.5.1, Repro: Affects 2.6
