### ISSUE TITLE
[TAStudio]Desyncs keep happening during TASing.  Possible solution.

### ISSUE THREAD

**Issue by EZGames69** [TASVideos/BizHawk#2186] opened 2020-07-01 20:20 UTC
So starting with BizHawk 2.3.3, there have been some nasty desyncs regarding TAStudio.  It involved the way clicking and dragging inputs work.  Before, when you clicked and dragged inputs in TAStudio, it would pause emulation (if emulation was unpaused while doing this), and wouldn't resume and load a savestate until you let go of the mouse button, but now it continues to playback while dragging, and every time you made a new input in the process, TAStudio would keep loading the previous state.

This becomes a problem when people do this in quick succession, and as a result, it may accidentally skip over some inputs and load an incorrect savestate.  Here is a video of it happening in real time: https://youtu.be/9S8ieyGd0pM

Direct your attention to this part:

![sggGyzlt](https://user-images.githubusercontent.com/44628443/86287262-e2fe1b00-bbb5-11ea-8dae-9e4a77b5135b.png)

This is the root of most of these desyncs.  Greenzone does not emulate these new input frames correctly, and may not even know those inputs exist.  This is why many of the current desync issues have been happening.  Granted, it was much worse back in 2.3.3, it seemes to have been improved in later versions, but I've been seeing this more consistently as recently as yesterday for a Genesis game.

Possible Solution: When dragging inputs, emulation should continue to pause until the mouse button has been released, only then should TAStudio load a savestate.  Since 2.3.3 was the first version of BizHawk I've seen that doesnt automatically pause emulation when dragging inputs, I feel it's safe to say this is why the desyncs have been happening.

**Comment by vadosnaprimer** [comment] 2020-07-01 20:24
There's a greenzone consistency check in dev builds. If you can figure out an easy way to make tastudio create a bad state that would fail this check, it will help A LOT.

**Comment by EZGames69** [comment] 2020-07-01 21:08
Recorded my attempts at recreating the bug, managed to accidentally get it first try.

https://www.youtube.com/watch?v=bqMeEXR-GRU

**Comment by adelikat** [comment] 2020-07-01 21:35
@feos, it's a mouse up issue caused by me and my "only do things on mouse up" approach.

**Comment by AleMastroianni** [comment] 2020-07-03 09:38
I get a desync so often it became almost impossible to tas now. I checked with the greenzone consistency and it gives bad states even when im not giving inputs at all, from frame 0 and so on. I tried with dev build aswell on a fresh movie and it gave me a bad data during a cutscene for the game (Crash Team Racing NTSC-U)

**Comment by adelikat** [comment] 2020-08-05 22:51
EZGames69 test and confirms this fixes the issue. Closing.

**Closed by adelikat** 2020-08-05 22:51 UTC
Labels: Repro: Affects 2.5 dev, Repro: Regression from 2.3.2, Tool: TAStudio
