### ISSUE TITLE
PCE/SGX 1941 BROKEN LATEST DEV BUILD APPVEYOR

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1203] opened 2018-05-30 03:53 UTC
Since bizhawk 2.2.2 2 pce games i noticed issues with were fixed but one is now broken

1941 as soon as you start level one the clouds draw funny.

This is not broken in earlier builds.

**Comment by jjfmz42015** [comment] 2018-06-11 15:13
for anyone else with this problem as a for now solution i went and downloaded the latest mednafen liberto core for super grafx and set bizhawk to load all pce/sgx roms with this core.

**Comment by jjfmz42015** [comment] 2018-07-19 19:40
waterbox mednafen?!?!?

**Comment by vadosnaprimer** [comment] 2018-09-14 05:29
Just bisect guys!

**Comment by Asnivor** [comment] 2018-09-14 09:27
Hmm, bisect really is great. I should use this more often :)

Anyway, this is the breaking commit:   https://github.com/TASVideos/BizHawk/commit/aa7cee1bb7d123f5ed9c136554bb8fae7d9d9b37

However, at this time I haven't got a clue where to start in trying to fix it....

**Comment by alyosha-tas** [comment] 2018-09-19 00:31
unfirtunately I don’t really remember what most of that commit is doing. Sometimes I think that the PCE core works just by chance. 

You can uncomment all the console.write stuff though and it should give you some decent diagnostic information. Usually the issues that pop up are related to one of those variables changing.

**Comment by Asnivor** [comment] 2018-09-19 09:54
So un-commenting those in **VDC.Render.cs** does nothing - its a supergrafx game rather than turbografx. So the issue is going to be related to the commit changes made in **VDC.cs** and/or **VPC.cs**

I can p*ss about changing things until something may or may not work, but ultimately I don't understand enough about the emulated tech itself at this point. If this commit actually fixed problems in other games, then I will almost certainly introduce regressions that I have no idea how to fix.

I'll probably bow out here now...

**Comment by Asnivor** [comment] 2018-09-26 09:39
@jjfmz42015 I believe this should be fixed now. Can you please test in the latest dev build and let us know?

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Closed** 2020-06-22 00:44 UTC
Labels: Bug (GoogleCode), Core: PCEHawk, Repro: Patch Pending

**Comment by nattthebear** [comment] 2020-06-22 00:56
Reopen if this still happens on the nyma core
