### ISSUE TITLE
Movie system Id () does not match the currently loaded platform (GB), unable to load

### ISSUE THREAD

**Issue by BlueYoshi-57EML** [TASVideos/BizHawk#2479] opened 2020-11-13 16:52 UTC
In TAStudio, I saved a TAS, opened it later but it keeps saying me this error and I can't load my TAS, what can I do to load my TAS?

**Comment by YoshiRulz** [comment] 2020-11-13 19:17
* What version are you using?
* Which core were you TASing on?
* Can you upload your movie here so we can try for ourselves?

**Comment by BlueYoshi-57EML** [comment] 2020-11-13 21:13
I'm using 2.5.2, i'm tassing in Gambatte and I can't upload my movie anymore, since I only saved the .tasproj and can't open it now.

**Comment by vadosnaprimer** [comment] 2020-11-13 21:33
> I can't upload my movie anymore, since I only saved the .tasproj and can't open it now

How does that prevent uploading the file?

**Comment by BlueYoshi-57EML** [comment] 2020-11-13 21:36
oh I thought you meant making a .bk2 out of the tasproj. Here it is:
[Mario's Picross (UE) [S][b2].zip](https://github.com/TASVideos/BizHawk/files/5539437/Mario.s.Picross.UE.S.b2.zip)

**Comment by YoshiRulz** [comment] 2020-11-13 23:02
```
$> unzip Mario\'s\ Picross\ \(UE\)\ \[S\]\[b2\].tasproj 
Archive:  Mario's Picross (UE) [S][b2].tasproj
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```
I think it might have been corrupted.

**Comment by vadosnaprimer** [comment] 2020-11-14 09:03
[Mario's Picross fixed.zip](https://github.com/TASVideos/BizHawk/files/5540407/Mario.s.Picross.fixed.zip)

**Comment by nattthebear** [comment] 2020-11-17 14:36
> 
> 
> [Mario's Picross fixed.zip](https://github.com/TASVideos/BizHawk/files/5540407/Mario.s.Picross.fixed.zip)

That seems to have the same `Header.txt` as the broken one.  What's going on here?

**Comment by vadosnaprimer** [comment] 2020-11-17 15:14
I removed the greenzone which got corrupted, causing the failed load somehow.

**Comment by nattthebear** [comment] 2020-11-17 15:51
Duplicate of https://github.com/TASVideos/BizHawk/issues/2392

**Comment by YoshiRulz** [comment] 2020-11-17 20:42
From https://github.com/TASVideos/BizHawk/issues/2392#issuecomment-698341923:
> The brokenness here matches 757ac4e reasonably well, so I think we fixed it

That commit was in 2.5.2, so either it didn't work or this is a separate bug. Reopening.

**Comment by nattthebear** [comment] 2020-12-15 16:42
@adelikat As a partial fix for this, could we `try { ... }` the greenzone load and if it fails, start with a new empty greenzone?

**Comment by vadosnaprimer** [comment] 2021-06-04 10:54
The project [provided here](https://github.com/TASVideos/BizHawk/issues/2479#issuecomment-727047081) still doesn't load btw.

**Comment by nattthebear** [comment] 2021-06-05 00:06
> The projects provided [here](https://github.com/TASVideos/BizHawk/issues/2479#issuecomment-727047081) and [here](https://github.com/TASVideos/BizHawk/issues/2574#issuecomment-761606878) still don't load btw, until you remove GreenZone from the archive.

That's an inaccurate characterization.  They do not load because the zip files are corrupt.  Uncorrupting the zip files lets them load.  It has nothing to do with whether or not the empty greenzone lump is present, so long as the overall zip structure is fine.

**Comment by nattthebear** [comment] 2021-06-05 00:14
I'm closing this issue because both provided projects give a very specific error on load that does not match the ticket title, nor the title of the other ticket:

```
System.IO.InvalidDataException: End of Central Directory record could not be found.
```

I think this might still be an issue, but it's one that we need a new, clean, reproduction of on current versions of Bizhawk, as some load machinery has changed.  Feel free to open a new issue when we have that.

**Closed by nattthebear** 2021-06-05 00:14 UTC
Labels: App: EmuHawk, Repro: Affects 2.5.2, Repro: Fixed/Added in 2.6, Tool: TAStudio
