### ISSUE TITLE
C64 file extension recognition error

### ISSUE THREAD

**Issue by Fortranm** [TASVideos/BizHawk#1413] opened 2019-01-02 06:25 UTC
.CRT files are not recognized as supported roms under "Rom Files", and .D64 files are not recognized as supported roms under "Commodore 64".

**Comment by YoshiRulz** [comment] 2019-01-02 07:55
Duplicate of #1392. Try the latest dev build, that issue was resolved by bcd3424.

**Comment by Asnivor** [comment] 2019-01-02 10:35
@Fortranm yup, as @YoshiRulz has said:

the .d64 issue is fixed here: https://github.com/TASVideos/BizHawk/commit/bcd34246acfe7cc709aa4c8638dce024dd5c401d#diff-8c2264ad8c85d3e11f6fc33d1e185f3bL2125

and the .crt issue is fixed here: https://github.com/TASVideos/BizHawk/commit/bcd34246acfe7cc709aa4c8638dce024dd5c401d#diff-5d2353e0730d26f86b1358041b5dc3f5R64

This *is* fixed in the latest dev build (here: https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts) and will be in the next production release.

**Closed by Asnivor** 2019-01-02 10:35 UTC
