### ISSUE TITLE
Genplus-gx [BizHawk] Game Genie codes not working

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#766] opened 2017-01-04 08:28 UTC
I can't get any Game Genie codes to work on BizHawk Genplus-gx. I have codes that I know that work but on BizHawk they don't work. I know how to use BizHawk. Like on the game Strider (UE) [!]. Here is a code that give you Infinite Life In The Life Gauge.

AK8T-AA5R
AKVT-AA94
AJLT-AA9E

On Kega this code works.

**Comment by hegyak** [comment] 2017-01-04 12:48
Can you tell me where you got the Code from?  Like gamehacking.org  Or somewhere else?  I can try and determine where the code is being improper based on what RAM Value(s) it is trying to interact with.

**Comment by Cibomatto2002** [comment] 2017-01-04 20:32
I got them from here.

http://gamehacking.org/game/15978

and checked to see if they matched form here.

http://gamegenie.com/cheats/gamegenie/genesis/strider.html

**Comment by hegyak** [comment] 2017-01-05 13:01
Confirmed Bug.

This is due to how I wrote the Cheats handling for BizHawk.  It is supposed to write two byte values to the address.  However, it is only writing single byte values to the address, which is the issue here.

**Comment by hegyak** [comment] 2017-01-05 13:10
Fixed with:
https://github.com/TASVideos/BizHawk/commit/5ccde9cc711c6ff75bb35ded035345ae61bdc5f1

**Closed by hegyak** 2017-01-05 13:10 UTC
Labels: bug, Core-EmuHawk, Core-Genplus-GX, Core-GensHawk, OpSys-Any, Priority-Medium, Type-Defect
