### ISSUE TITLE
Single Instance Mode - Throws exception: window title can only be changed by calling UpdateWindowTitle (which calls WindowTitle getter)

### ISSUE THREAD

**Issue by DartPower** [TASVideos/BizHawk#2577] opened 2021-01-17 21:25 UTC
```
System.InvalidOperationException: window title can only be changed by calling UpdateWindowTitle (which calls WindowTitle getter)
   в BizHawk.Client.EmuHawk.FormBase.set_Text(String value)
   в BizHawk.Client.EmuHawk.Program.SingleInstanceController.OnCreateMainForm()
   в Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   в Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   в Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   в BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
Just downloaded 2.6 and configured (IDK which parameter throw this crash)

**Comment by YoshiRulz** [comment] 2021-01-17 21:27
That would be caused by single-instance mode.

**Comment by DartPower** [comment] 2021-01-17 21:28
Yes, this problem. Disabled single-instance in config and works.

**Comment by YoshiRulz** [comment] 2021-01-17 22:52
I assume this bug has existed since `FormBase` was added in aa1de1c9d.

The single-instance feature has been due for a rewrite for forever, so I'm going to close this as wontfix, remove the feature from master, and [let zeromus deal with it :D](https://github.com/TASVideos/BizHawk/pull/2342#issuecomment-683341507).

**Closed by YoshiRulz** 2021-01-17 22:52 UTC
Labels: App: EmuHawk, Repro: Affects 2.6, Repro: Regression from 2.5.1
