### ISSUE TITLE
N64 - Crusi'n Exotica, Missing textures in Exotic modes.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#181] opened 2015-06-22 14:35 UTC
```
What steps will reproduce the problem?
1. Beating Exotica mode and unlocking Exotic options (Wicked/Insane)
2.
3.

What is the expected output? What do you see instead?
Expected output is ...colourful textures.  Instead there all missing.

What version of the product are you using? On what operating system?

SVN66666, windows 7 64bit, Radeon 7850 Catalyst 14.4

Please provide any additional information below.

I suspect this is more a problem with mupen and/or the video plugins and not 
bizhawk it self.

All 3 video plugins have this error although Rice plugin shows it a bit 
differently.  Also with Rice, I can very slightly improve the image by setting 
N64 native textures.  In rice I can also enable 'Normal Colour Combiner' which 
makes everything look more normal but still missing backgrounds and 
transparency.

I have included a savestate which start on the games ending credits screen.  
The game forces Exotic mode so It can t be viewed without it.  If you press 
start and go to the game options, you can enable the Exotic modes and see the 
result on the car selection screen before going into a race.

```

Original issue reported on code.google.com by `MThompso...@gmail.com` on 23 May 2014 at 9:36

Attachments:
- [Cruis'n Exotica (USA).png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-181/comment-0/Cruis'n Exotica %28USA%29.png)
- [Cruis'n Exotica (USA).State](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-181/comment-0/Cruis'n Exotica %28USA%29.State)

**Comment by vgturtle127** [comment] 2017-06-04 23:44
I can't reproduce this on newer versions of BizHawk, so is the issue fixed?

**Comment by adelikat** [comment] 2017-06-05 00:09
I guess I'll close it then.  It can be reopened if there's more to it

**Closed** 2017-06-05 00:09 UTC
Labels: auto-migrated, Core-Mupen64Plus, Priority-Low, Type-Defect
