### ISSUE TITLE
Metroid II: Return of Samus doesn't load.

### ISSUE THREAD

**Issue by TheMetroid7998** [TASVideos/BizHawk#2597] opened 2021-01-28 20:12 UTC
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Simply put, Bizhawk [v2.6] refuses to load Metroid II and any of its romhacks. Core loaded is Gambatte, but the other 2 are broken as well. I've tried changing the name, (because I saw the 'illegal characters in path' line in the error report) no dice.

Unmodified Rom Hash: SHA256 - 3080BCC2EB9965DE463F5F4E02F0DABBB13B060E1654A18DA8B50948C10AF4A6

### Repro
1. Aquire a copy of Metroid 2. This can be the original Gameboy version or the EJRTQ rom hack.
2. Attempt to load the room via any means, either by setting a file association, opening in bizhawk, etc.
3. Get the error message.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
---------------------------
load error
---------------------------
A core accepted the rom, but threw an exception while loading it:

System.ArgumentException: Illegal characters in path.

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

   at System.IO.Path.GetExtension(String path)

   at BizHawk.Common.HawkFile.<>c__DisplayClass36_0.<BindByExtensionCore>b__1(HawkArchiveFileItem item)

   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at BizHawk.Common.HawkFile.BindByExtensionCore(Boolean first, String[] extensions)

   at BizHawk.Client.Common.RomLoader.HandleArchiveBinding(HawkFile file)

   at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, String launchLibretroCore, String forcedCoreName, Int32 recursiveCount)
---------------------------
OK   
---------------------------

```

### Host env.
- BizHawk 2.6; Win10 Home 20H2; Intel/NVIDIA
[//]: # "
![image](https://user-images.githubusercontent.com/78174372/106193196-0bf18900-6162-11eb-96a7-d4e27a8a613f.png)
"

**Comment by nattthebear** [comment] 2021-01-28 20:57
Duplicate of https://github.com/TASVideos/BizHawk/issues/2587

**Closed by nattthebear** 2021-01-28 20:57 UTC
