### ISSUE TITLE
[NLua] Crash while reading in .wch file using io.lines()

### ISSUE THREAD

**Issue by Isotarge** [TASVideos/BizHawk#1115] opened 2018-02-15 13:58 UTC
I'm using io.lines() to read and parse a .wch file for use in a Lua script, seems to work great with the LuaInterface backend, but with NLua (currently the default backend) it crashes after reading the final line.

Thankfully it doesn't crash BizHawk, just prevents the script from running with a blank error message, but still not ideal to have to tell my users to switch backends.

The code I use to read in files is available here for reference https://github.com/Isotarge/ScriptHawk/blob/0762b1e12deaefdee13f802a5d167795e56bee54/lib/LibScriptHawk.lua#L364

**Comment by zeromus** [comment] 2018-02-15 17:15
nlua file IO will never properly work. Mimicking lua's stdio file IO functions with .net file IO is impossible, and nlua has barely tried. Your best bet here is getting with feos and convincing everyone that nlua is no longer needed since I fixed (apparently) the luainterface problems, so we can just delete nlua.

**Comment by vadosnaprimer** [comment] 2018-02-15 17:55
Well I confirmed that the luainterface fixes work, and I can check harder if needed. The only thing I wanted nlua to stay for, portability, isn't quite happening without mono. And even there people succeeded to make luainterface work:
https://github.com/TASVideos/BizHawk/issues/1093

**Comment by Isotarge** [comment] 2018-02-16 00:47
Alrighty. I understand NLua sticking around for portability reasons but can we default to LuaInterface again for the next release so I can use file IO without worrying about users switching backends?

**Comment by brunovalads** [comment] 2018-03-07 20:14
Agree with Isotarge, LuaInterface should be default since it's fixed now and runs faster than NLua. Perhaps NLua could be the default for mono then.

**Comment by vadosnaprimer** [comment] 2018-03-08 21:03
Fixed in https://github.com/TASVideos/BizHawk/commit/900a9e53226ebd948db9c529fd207b2abf963ecf

**Closed by vadosnaprimer** 2018-03-08 21:03 UTC
