### ISSUE TITLE
[Octoshock] MGS cutscenes stutter when on a modern HDD - preload .bin to RAM suggestion.

### ISSUE THREAD

**Issue by dart193** [TASVideos/BizHawk#2745] opened 2021-05-18 13:00 UTC
When playing PSX Metal Gear Solid (USA), the game works fine and can run up to 200 FPS if turboed, but during cutscenes it sometimes stop for about full second before continuing emulation. This is not emulated console not working - framerate falls from 60 FPS to 0 FPS during this. So far, I have not noticed the same issue with other games. Some other games would stutter internally in the PSX with measured FPS always being 60, but this is not the case here.

However, when using RAM drive (Dimmdrive being specific program), no such issue happens. The difference between running normally and via RAM drive is that .bin files are read from RAM instead of disk. This pinpoints the issue to the speed of seeking in the .bin file. Looks like there is a lot of things going in the cutscene that require more intense than usual access to the psx disk which does not seem to go good with reading said disk from hdd.

I remember some other emulators having "Preload contents of ROM in the memory". This option allowed me to run ROM based games with no issue on machines with slow HDD. Nowadays, disks have reading speed of 100 MiB/s, so no issue with ROMs. But ISOs are much larger and seems to still suffer from this issue.

Given the fact that modern PCs have lots of RAM, PSX ISOs (cue/bins) for a single disk would fit into RAM with no problem. Multidisk games may not have enough space in the RAM on the lower end machines, but will still fit easily otherwise, even 4 disk giants.

I am asking of adding the option to allow caching PSX ISOs (.bin files) to the RAM instead of reading them from HDD. If possible, the same option can be enabled for multi-disk bundler when multiple PSX disks are selected.

Machine running BizHawk:
HP Pavilion Power 15 cb-0xx series.
Measured HDD read speed: >120 MiB/s. Kinda odd that this speed is not enough.

**Comment by YoshiRulz** [comment] 2021-05-18 19:19
Duplicate of #2674/#2675.

**Closed by YoshiRulz** 2021-05-18 19:19 UTC
Labels: App: EmuHawk, Enhancement

**Comment by zeromus** [comment] 2021-05-18 20:04
not a dupe, because it's about bad seek times and not spin-down.
user needs to defrag his hard disk and check it for errors.
user also has a ramdisk workaround for his deficient hardware, so this is not high priority

**Comment by dart193** [comment] 2021-05-19 12:05
Defrag was done but it has no effect. I suspect that it has something to do with the way Windows processes fseek(FILE * file, int pos, int origin) (or alternative). I have been working with FILE to access file and must say that this thing is terribly slow if not used optimally. Since the scene has music played in the background I suspect the PSX has to quickly switch between one track and the other, which means fseek has to be executed in the image since file can only be read forward sequentally, and that can cause delay from none to seconds if the Windows feels particularly bad.

Another thing is that the further I am in the game the worse the issue gets. Looks like later cutscenes require accessing later part of the file which means more time to seek to that part.

Of course, I do not know which method is used for seeking in the image file, this is just a speculation from the experience. BizHawk might not even use fseek itself, though things like Qt or other libraries are not exactly faster.

Another thing is that this is indeed not about spin down since the game reads the disk about 99% of time due to the need of playing BGM and cutscenes are intense about disk read. Windows task managed shows constant access to the disk at the speed of 0.3-0.5 Mbit/s, I save often (forcing some writes to the disk) and I do not hear disk stopping. That only even happens if I play ROM based games and do not use save states for a prolonged period of time.

And yeah, this is more of a suggestion rather than a bug, but I could not find if there is a suggestion section. I also swear I checked if this was brought up before, but I guess I did not used correct search terms. My bad.

**Comment by zeromus** [comment] 2021-05-19 18:02
Metal gear solid doesn't use cd audio for music. This game should be no different than any other game. Use a better defragger and scandisker. Backup your files, too, because most likely explanation is your disk is about to die. Hard disk seek time is superior to CDs in every case, except when the hard disk is about to die. At that time it will begin stashing data all over the disk to try and find locations that aren't going bad. It may also be discovering that data is going bad while reading it and copying it to other places.

**Comment by dart193** [comment] 2021-05-19 19:56
Highly unlikely, as S.M.A.R.T. shows the same amount of bad clusters as it had when it was bought (disks frequently come with bad sectors right away which are already remapped on a hardware level), and clusters pending remapping reads zero. In all the experiences I had imminient disk failure, there were distinct messages in windows logs regarding NTFS file system failing. No such messages exist. Also, I do not see how a different defragger would help if the file fragment count is ONE, which means its not fragmented. Also, bad sector issues usually take about 5-15 seconds to process once they occur, at least in my experience.

This also does not explains why further parts of the file take longer time to seek to. That the game does not uses CD music is a surprise to me however, readings show that this is indeed the case with many games. Still, its odd that the game itself works fine even though disk LED is ON all the time.

Anyway, I have finished the game and did not found any other issues besides this one. I will try to verify this issue with this game on a different hardware when I get the chance. If the issue will repeat itself, it would be possible to rule out hardware dependency, however all my machines have Samsung disks, so a driver issue would not be ruled out.

**Comment by zeromus** [comment] 2021-05-19 20:23
The game seems to read several sectors repeatedly (exactly which sectors changes over time). Maybe it's keeping voice acting warmed up, or maybe it's a bug in the emulation. So that's why the disk light is on constantly. So... the game is different than other games in that respect.  If it's an emulation bug then it's possible sectors would be read in a scattered way while other activity is going on, which would be an unnatural random access. However, your OS should have recent sectors cached, unless the drive is misconfigured somehow. Anyway, a hard disk should be able to do one seek per frame but if it's doing more than that, we may have trouble. 

One other interesting thing: Blob_RawFile.cs is configured to read ~300KB of data at once. You might reduce that to 2352 bytes only (or skip the BufferedStream entirely) and see if it improves matters for you. I don't think it should. Once the disk is seeked, the amount of data read is small in any event.

**Comment by dart193** [comment] 2021-05-19 23:00
OS is for sure does no other junk since, if I pause the emulation, then the HDD spins down, meaning that the OS does not accesses it for its own need neither there are any other apps running.

As for caching, should be, except that Win 10 has caching bug which both affect ability to use all the RAM available and to actually access cached data. I do not know if this bug is related to that, but the disk activity is constant while HDD light off meaning that the data is indeed being read from cache unless the read time is so short that the light is on for too short time to be visible.

As of seeking, if I correctly understand the way file partitioning work, there is some overhead required to get the information where the seekable part of the file lies physically on the disk. If I am not mistaken, list of clusters of the disk that contain data is a linked list. That means that to reach, say position 400 MiB away from the start of the file, the OS would need to process 100 000 pieces of information if the cluster size if 4KiB. If the file is processed sequentally, the time system spent processing the next cluster is insignificant in comparison to the time it takes to read the data from the disk.

If the game is repedeately accessing some data that is very close together on physical CD disk, the console would need to do minimal head movement and would be able to read data quickly. But on HDD, if fseek function that is supposed to move the position in file stream is called via offset from the beginning of the file rather than the current position, it would cause giant overhead to read data from the middle of the file, even if it is cached. That would perfectly explain why later cutscenes lag worse than earlier ones on both discs.

However, I am not all that much sure of how exactly Win 10 handles seeking data in file. I can only say from my experience that reading a file several MiB in size is significally faster to do all at once and then process in memory than to read the data using fseek, process read data, fseek again, process, repeat until the file is read completely, even when the file is already cached by OS and is not using actual HDD access. I simply suspect that this problem might be related.

Is it possible to check how exactly position in the file is seeked?

**Comment by zeromus** [comment] 2021-05-19 23:13
I dont know how ntfs works, but your understanding is certainly wrong. Random access is not a general problem. Seeking is not a general problem. There is overhead associated with each operation but it has nothing to do with where in the read cursor is. Anything that combines several disk operations into one will be faster.

You can't assume that there is any correlation between where in the game a cutscene is and where on the disk the data for it is. And anyway that's predicated on the later-sectors-are-slower-on-the-filesystem theory which is 100% bunk.

Simplest explanation at this point is that there's simply a bug in the emulation that causes the emulation to hang up for a long time and the disk access pattern is a red herring. You should see that the cpu is pegged when that happens.  Post a savestate so someone else can check this.

**Comment by dart193** [comment] 2021-05-20 12:19
Yep, all I said is nonsense: I missed the fact that seek processing would be the same for both HDD and RAMdisk.
