### ISSUE TITLE
Rewrite the TAStudio State Manager

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2288] opened 2020-08-12 11:32 UTC
The current one was created without any real knowledge of what the State Manager is and needs to do.  It has significant shortcomings and cannot be salvaged.

**Comment by alyosha-tas** [comment] 2020-08-12 13:20
I don't know what zwinder is or what it was intended to fix, but TAStudio seemed to work just fine before it but is pretty broken now. Can it just be reverted? Maybe such a major rewrite can wait until after 2.5 is released, since several major bugs had already been fixed in TAStudio.

**Comment by RetroEdit** [comment] 2020-08-12 13:44
@alyosha-tas This is actively being discussed in IRC, but zwinder just behaves a little differently than the old StateManager; it's not "broken" per se.

The issue here is that zwinder doesn't re-greenzone during normal playback of an older part of the movie, it only does so once a section has been invalidated.

This probably needs to be addressed, but it may be possible to address without completely ripping out the zwinder state manager.

**Comment by RetroEdit** [comment] 2020-08-23 23:16
I don't think writing a new state manager is necessarily a bad idea, especially for cores where the savestate size is fairly consistent. There may be some performance/organizational gains there. That said, as long as the zwinder state manager is workable for TASing, writing a totally new state manager is probably not a large priority.

**Comment by adelikat** [comment] 2020-08-31 17:11
We salvaged it pretty nicely.  And maybe it is still a disaster as 2.5 ages and bug reports come in.  However, I still want to close this ticket.  If we need to rewrite it, a ticket should be opened with an actual idea that is better than what we have, and a plan

**Closed by adelikat** 2020-08-31 17:11 UTC
Labels: Repro: Affects 2.5 dev, Tool: TAStudio
