### ISSUE TITLE
GLideN64 Regression

### ISSUE THREAD

**Issue by nlburgin** [TASVideos/BizHawk#1646] opened 2019-08-23 01:16 UTC
There's a strange glitch happening in GLideN64 on Mario Golf in Bizhawk 2.3.1 and 2.3.2 (as well as latest interim build)

It looks like this.

![Mario Golf (U)  ! 2019-08-22 17 59 19](https://user-images.githubusercontent.com/30382228/63559643-a6d34600-c520-11e9-8349-0f37ee5e0160.png)

The texture is blacked out on the fairway, the tee box, and the green.

However, on 2.3.0, it looks like this:

![Mario Golf (U)  ! 2019-08-22 18 02 22](https://user-images.githubusercontent.com/30382228/63559571-4f34da80-c520-11e9-8300-4f6f13c464e8.png)

which is clearly a lot more normal. The sync settings were exactly the same between these two pictures. In fact, this result can also be achieved on 2.3.2 if you simply swap out its copy of `mupen64plus-video-GLideN64.dll` with the older one that came with 2.3.0.

I initially assumed this was an upstream regression, but when I tested the latest upstream GLideN64 with the latest upstream Mupen64Plus, the glitch did not occur. So it seems like it has to be a Bizhawk issue, then.

Interestingly, the upstream DLL did not seem to be compatible with BizHawk.  As I mentioned it worked fine with regular M64+, but when I tried it with Bizhawk, it did this:

![Mario Golf (U)  ! 2019-08-22 18 15 22](https://user-images.githubusercontent.com/30382228/63559958-054cf400-c522-11e9-8c04-a10c6ecf80b1.png)

Which is definitely worse. Although from what little I can make out through the complete scramblage, at least the texture glitch appears to be absent :stuck_out_tongue_closed_eyes: 

Incidentally I was on IRC (as "Question48") and someone suggested removing all the Mario Golf related lines from `gamedb_n64.txt`, but that had no effect. So, it seems like the answer isn't in there.

**Comment by zeromus** [comment] 2019-08-23 01:36
bizhawk is not using the latest upstream gliden64, so it's not proof of anything.
the only interesting proof of anything would be demonstrating a gilden64 version that had that bug on mupen. ideally, the version we last merged.

additionally it would help if someone merged the latest gliden64 code, since you did test that version on mupen. it's possible it will work again in bizhawk

**Comment by nlburgin** [comment] 2019-08-23 01:50
>ideally, the version we last merged.

Would that be [this](https://github.com/TASVideos/GLideN64/commits/master)?

Unfortunately, that commit is over six months old, so its [appveyor artifacts](https://ci.appveyor.com/project/gonetz/gliden64/builds/21935613/artifacts) got automatically deleted. I'm not confident trying to build it from source.

**Comment by zeromus** [comment] 2019-08-23 01:54
no, that's the master branch. the last version we merged is in the branch_bizhawk branch

**Comment by nlburgin** [comment] 2019-08-23 02:02
Oh. Well in that case it looks like the latest merge _was_ Public Release 4.0, which is what I tested, and what I meant when I mentioned the latest upstream Gliden. I wasn't using an interim dev build of gliden, just the most recent _release_. 

So it looks like the version that was merged last _was_ the one I tested after all.

**Comment by nlburgin** [comment] 2019-08-23 02:06
It might be worth noting that I could only find a 32-bit build of upstream M64+ for Windows, so when I tested upstream Gliden with it I also used the 32-bit version library.

Whereas I'm pretty sure everything to do with Bizhawk was 64-bit.

I wouldn't _think_ that would be related to anything like this, but IDK.

**Comment by nlburgin** [comment] 2019-08-23 02:23
It also might be worth mentioning that in all cases I was using OpenGL 3.3. core profile.

I think gliden is designed do things somewhat differently internally depending on what OpenGL version it detects. So I'm not 100% sure if the bug would be reproducible in an OpenGL 4.x environment due to different code paths possibly being involved.

IDRK, it just seemed worth mentioning.

**Comment by vadosnaprimer** [comment] 2019-08-23 15:32
We've seen bugs that were only caused by the way we forked gliden, it's probably one of those.

**Comment by vadosnaprimer** [comment] 2020-02-04 07:48
Test latest master https://ci.appveyor.com/api/buildjobs/q2ljwvqdlagif065/artifacts/BizHawk_Developer-2020-02-04-072710-%238ff2ca2cd19d3280a45ab498c72f5d99785adc1d.zip
Might not help at all, but there's not a lot we can do with our 7 year old core.

**Comment by nlburgin** [comment] 2020-03-20 16:44
I couldn't even get the dev build to run...

However, I *can* confirm that my workaround of simply copy-pasting the `mupen64plus-video-GLideN64.dll` from 2.3.0 to the newer version still works in the latest stable release 2.4.0

**Comment by vadosnaprimer** [comment] 2020-06-08 18:06
Main issue should be https://github.com/TASVideos/BizHawk/issues/1718

**Closed by vadosnaprimer** 2020-06-08 18:06 UTC
Labels: Core: Mupen64Plus, Repro: Affects 2.3/2.3.1/2.3.2, Repro: Patch Pending, Repro: Regression from 2.3
