### ISSUE TITLE
mGBA BIOS skip does not work

### ISSUE THREAD

**Issue by Weirwindle** [TASVideos/BizHawk#1566] opened 2019-05-15 01:27 UTC
sornerol- "This seems to be a duplicate of #1432, which has since been fixed." ... "This issue is closed"
You did not read well enough. This is not a duplicate. Different core, same problem.
#1432 had a problem with the **VBA** core not skipping BIOS (which was fixed)
This post if for the **mGBA** core. It will not skip BIOS even when "Skip BIOS" is set to true, even in newer development versions.
This problem is **NOT** fixed.

**Comment by YoshiRulz** [comment] 2019-05-15 01:56
Duplicate of #1540.

**Closed by YoshiRulz** 2019-05-15 01:56 UTC
