### ISSUE TITLE
Virtual Pad buttons get stuck + crash

### ISSUE THREAD

**Issue by staticfox** [TASVideos/BizHawk#786] opened 2017-01-28 07:17 UTC
### Current setup:
* Windows 10
* Downloaded from AppVeyor Artifact commit dd19a69b6
* Super Mario 64 (USA)

### Steps to reproduce
1) Load EmuHawk.exe
2) File -> Open Rom -> Super Mario 64 USA
3) Tools -> TAStudio
4) Tools -> Virtual Pad
5) Click S (or A, B, Z, doesn't matter)
6) Advance a frame in TAStudio (Or hit play/pause)
7) The selected button from step 5 is now stuck until you start the entire emulator

If you try to close Virtual Pad and TAStudio then load TAStudio it throws this exception:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at BizHawk.Client.EmuHawk.InputRoll.DoBackGroundCallback(PaintEventArgs e, List`1 visibleColumns)
   at BizHawk.Client.EmuHawk.InputRoll.DrawBg(PaintEventArgs e, List`1 visibleColumns)
   at BizHawk.Client.EmuHawk.InputRoll.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Let me know if you need any additional information. Thanks!

**Comment by vadosnaprimer** [comment] 2017-02-04 19:51
Switch to recording mode in tastudio to use virtualpad.

**Comment by alyosha-tas** [comment] 2018-11-29 00:41
This also seems fixed I think? It seems to work as intended now without crash.

Might want to double check @vadosnaprimer

**Comment by vadosnaprimer** [comment] 2018-11-29 17:41
I don't have time atm. If it works just close it.

**Closed** 2018-11-29 22:43 UTC
Labels: Topic-TAStudio
