### ISSUE TITLE
2.4.1 Windows version Display Configuration Scaling & filtering broken.

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1978] opened 2020-05-04 13:58 UTC
2.4.1 Windows version Display Configuration Scaling & filtering broken.

in 2.4 and previous is ok.

Example try opening config and set custom aspect ratio. go back in custom ratio gone and not retained.

**Comment by jjfmz42015** [comment] 2020-05-04 14:01
custom aspect ratio broken on this windows build.

**Comment by YoshiRulz** [comment] 2020-05-04 21:09
Duplicate of #1975?

**Comment by zeromus** [comment] 2020-05-04 21:11
yes

**Closed by zeromus** 2020-05-04 21:11 UTC
Labels: App: EmuHawk, Repro: Affects 2.4.1, Repro: Regression from 2.4
