### ISSUE TITLE
Hang on Undo Copy and or Paste

### ISSUE THREAD

**Issue by TiKevin83** [TASVideos/BizHawk#1822] opened 2020-01-28 16:28 UTC
TAStudio tends to hang for long periods of time (10 minutes to an hour) when using ctrl-z undo or ctrl-c+ctrl-v copy+paste.  The hangs don't seem to completely crash the emulator, just hang for such lengths of time.  I've seen this myself specifically when undoing in GB+Gambatte but I don't think it's core related as I've heard others having issues in SNES.

**Comment by adelikat** [comment] 2020-01-28 16:29
how many rows are you trying to copy/paste?

**Comment by TiKevin83** [comment] 2020-01-28 16:34
The most specific case I can relate was undoing a single frame input change around frame 5000 of a 30k line movie.  Changing the input doesn't hang, but then an undo of that input does hang.  When copy/pasting I would like to use 7-8 frames of inputs, but the specific problem I reproduced myself was with undo, I haven't tried to use copy paste in forever due to the hangs.

**Comment by adelikat** [comment] 2020-02-02 18:10
Do you have "Bind markers to input" on?

**Comment by TiKevin83** [comment] 2020-02-14 01:57
I hadn't touched that setting and it looks like it's off by default

**Comment by adelikat** [comment] 2020-03-29 20:49
with bind markers to input off, and a 40k movie.  I can edit frame 5k or so and undo.  I can copy and paste, and copy paste+insert, almost insantly.  I am unable to reproduce this.

**Comment by NotFx** [comment] 2020-04-08 23:30
Having the same issue. Using ctrl-z to undo frame inserts or deletes causes Tastudio to freeze for prolonged periods of time. I only use mGBA so I can't comment on other cores.

When launching Tastudio it's fine, I can ctrl-z just fine; it works as you'd expect. But if I turbo-seek through increasingly large amounts of frames, the functionality of ctrl-z on inserted or deleted frames becomes slower and slower. After a 15k seek it's already noticeably slower for me. Slower is still workable though; but my current project is several hundreds of thousands of frames long by now, and when turbo-seeking through a new bk2 of the project, the ctrl-z functionality might as well not exist for me at all. Simply calling on it will freeze Tastudio for faily large amounts of time (upwards of a few minutes has been my worst experience so far).

So for me, the reproduction method is to just load a movie significantly large to the point where Tastudio cannot store the entire thing in RAM, and then delete or insert frames somewhere, continue playing the movie (even for a couple hundred frames) and attempt to ctrl-z, Tastudio and Emu will freeze (and eventually execute the ctrl-z and continue working as if nothing happened).

**Comment by YoshiRulz** [comment] 2020-04-08 23:34
Can we have 1. your version of BizHawk, and 2. your RAM capacity? You too @TiKevin83.

Both of you could also try to repro after backing up `config.ini`, in case your memory usage settings are at fault.

**Comment by NotFx** [comment] 2020-04-08 23:50
Interim commit 32373542a (according to the help>about tab) from early March iirc.

16GB RAM. The memory usage settings always reset to defaults after closing, no matter what I've tried in the past.

**Comment by TiKevin83** [comment] 2020-04-29 19:22
I can't reproduce this as of current master

**Comment by adelikat** [comment] 2020-04-29 19:32
Going to close it, I think my commit from a few days ago might have fixed the issue, it mostly certainly fixed some scenarios, it is just a question of which

**Closed by adelikat** 2020-04-29 19:32 UTC
Labels: Priority: Critical, Repro: Could not reproduce, Tool: TAStudio
