### ISSUE TITLE
"LocLabelEx" seems to be "Limited Options for Configuration Label - EXtremely poopy"

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#2284] opened 2020-08-11 03:26 UTC
This commit did a mass replace of System.Windows.Forms.Label with LocLabelEx: 64d14a7f9213f176ccb48b90307acfb768c56ac2
In at least one case (and probably dozens more) this broke a dialog, because LocLabelEx seems to exist for the sole purpose of removing features from Label. Check SoundConfig.Designer.cs - note that AutoSize, Size, and TabIndex are removed. Uhhhh they were NEEDED? Check the dialog now -- it's broken with a label overflowing irrationally

I don't know what the rationale was for this change, but it doesn't make any sense to me.

**Comment by YoshiRulz** [comment] 2020-08-11 03:42
I caught two regressions at the time, too: 05eaf2cfb

**Comment by zeromus** [comment] 2020-08-11 03:51
I do not like fixing this with a newline. Can we fix the LocLabelEx so that it works like a normal label? It's stupid to lay out newlines by hand when previously we could simply size a label.

**Comment by YoshiRulz** [comment] 2020-08-11 03:55
The semantics of `LocLabelEx` are to be autosized. Instead of newlines in `Text`, we could add a new control, or just use `Label` with `AutoSize = false` (like before the change).

**Comment by zeromus** [comment] 2020-08-11 04:11
I don't know how you expect anyone to pick from 100s of customized variants of a label that prescribe different assortments of options.  Seriously, I'm supposed to pick from LabelEx, LocLabelEx, LocSzLabelEx, and SzLabelEx? This must be a joke.

So no, I don't propose adding YET ANOTHER. This whole subject is stupid. The maintenance nuisance of continually-edited designer files is NIL compared the to maintenance nuisance of the files MOVING in git, which is already done, so I don't really accept this as a significant rationale.

If I find many more of these dialogs broken by this I'm likely to revert them ALL.

**Comment by nattthebear** [comment] 2020-08-11 11:49
I raised my eyebrows at that commit, but ultimately didn't pursue it because I've sworn off all winforms development.

**Comment by adelikat** [comment] 2020-08-15 18:14
"I do not like fixing this with a newline. "

Indeed, the obvious fix it to put the relevant labels back to just being Label.  There's no law that it must be the Ex version

**Comment by adelikat** [comment] 2020-08-31 17:19
Closing this ticket.  If you see any specific labels that are a problem, either fix by using a normal label, or make a new ticket and assign to me, about a specific problem.

**Closed by adelikat** 2020-08-31 17:19 UTC
Labels: App: EmuHawk, Repro: Affects 2.5 dev, Repro: Regression from 2.4.2
