### ISSUE TITLE
Gba emu cores dont store cheats in .cht file

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1796] opened 2020-01-16 14:48 UTC
When you input a code in cheat converter that are compatible and click convert the code dont store in the list and when you input a formar that not support the bizhawk not show the dialog box say code is insuported by emu the versión is bizhawk 2.2.3

**Comment by YoshiRulz** [comment] 2020-01-16 17:57
What code(s) are you converting?

If you write your comments in your native language (Spanish?) and in English, it might be easier for me to read.

**Comment by DarkLegend1987** [comment] 2020-01-16 18:41
Ok sorry im an intermediate English is you speak spanish be good im testing the new build and check gba conole im used harmony of dissonance rom and try this code Potion 320187A0 0063 when im click convert the code dont appear in the list or is the format not support bizhawk not show warning say unsoported cheat format im speak with other testers and they the same

**Comment by hegyak** [comment] 2020-01-24 21:35
This appears to be an Codebreaker/GameShark SP/Xploder:

Source:
https://gamehacking.org/game/4115

On that page, under "Have Items Codes"
Look for the Word "Potion"  Then you can see the Code in the various formats there.

Now to the issue:
I programmed the Cheat Code converter but the GBA was probably the, least completed part of the entire thing.  So, not all cheat code types, were handled or handled properly.  Try using another format for the Cheat Code.

Try using the GameShark Advance/Action Replay Code instead of the Codebreaker.

**Comment by RetroEdit** [comment] 2020-08-16 11:44
The root cause of this issue appears to be #897, so closing this issue in favor of that one.

**Closed by RetroEdit** 2020-08-16 11:44 UTC
Labels: App: EmuHawk, Core: mGBA
