### ISSUE TITLE
TAStudio Desync - 2.5.2

### ISSUE THREAD

**Issue by The8bitbeast** [TASVideos/BizHawk#2560] opened 2021-01-11 11:18 UTC
I tried 2.5.2 and am still getting the type of desyncs that were introduced back in 2.3.3

I don't know how to replicate this but I did capture the entire session from opening TAStudio on video. Here is a link at the timestamp of the desync: https://youtu.be/Q_Qs1lhPF38?t=1821

I also noticed some other desyncs earlier in the session but didn't stop to check them out.

Since 2.3.3 I've had this desync on NES, SMS and N64 cores over multiple games.

**Comment by alyosha-tas** [comment] 2021-01-11 14:58
Do you always TAS with 'auto restore last position' checked?

**Comment by alyosha-tas** [comment] 2021-01-11 18:41
<a href="https://imgbb.com/"><img src="https://i.ibb.co/TWmDQqF/gap.png" alt="gap" border="0"></a>

This capture comes from 30:22 in the video. Here you can clearly see a gap in the greenzone that I am pretty confident caused this desync..

Directly before this, I saw inputs (right direction) being removed at the same time the game was playing / seeking, start at about 30:20 to see it.

So far I am unable to recreate this effect, games are always paused when I have a cell clicked on in TAStudio.

I briefly looked at other instances in the video where click and drag is used and didn't see any similar errors, so there must be some somewhat unusual trigger conditions.

@The8bitbeast where else were the desyncs that you noticed? If a similar gap appears elsewhere in the video it would confirm it least the cause

**Comment by The8bitbeast** [comment] 2021-01-11 23:01
Hey Aloysha,

Most of the time I TAS with autorestore on and I'm fairly sure I was holding the frame advance button at that point in the video if that helps. I agree that that video section is most likely the desync cause.

I can't easily point to any other desyncs in the video but I'm going to try to replicate desyncs today with a keyboard and mouse input display.

**Comment by alyosha-tas** [comment] 2021-01-11 23:42
Ahh holding the frame advance key. Yup I tried just now and I was able to get a state gap almost immediately with holding the key and painting inputs with the mouse.

**Comment by The8bitbeast** [comment] 2021-01-11 23:46
Oh cool, hopefully that can lead to the fix. I managed to replicate it again too with inputs. Let me know if you need the video, but by the sounds of it you wont

**Comment by vadosnaprimer** [comment] 2021-01-12 07:56
Once something looks suspicious, there's an option to verify tastudio greenzone integrity in dev builds. Helps with desync testing.

**Comment by alyosha-tas** [comment] 2021-01-12 16:38
https://github.com/alyosha-tas/BizHawk-Test-Files/blob/main/state_test.tasproj

Here is the simplest case I could reproduce. 

The game is NES Inversion. 

If you load up the TASproj and look at the last greenzoned frame, you will see the game has started despite there being no inputs.

I made this by painting inputs (and later removing them) with mouse while holding the frame advance key. I had 'follow cursor' checked but 'auto-restore last position' was not checked, so that particular setting doesn't matter.

Integrity checker did fail and pointed out the problem on the frame where start would previously have been pressed.

**Comment by alyosha-tas** [comment] 2021-01-12 22:07
I don't know what the underlying here problem is, maybe some event callback timing stuff.

I think the safest thing I can do here is to just block all frame advance operations while input is being input into the piano roll by mouse movement in TAStudio. This would have a pretty small footprint and only take effect in this limited case. 

I tried this and can no longer get any state gaps. Unless anyone else wants to look deeper into this, I'll commit the fix.

**Comment by adelikat** [comment] 2021-01-12 22:09
can you do a PR of your fix, so I can take a look?

**Comment by adelikat** [comment] 2021-01-13 02:33
Ok, looks good, and I merged it, let's see if this fixes these desync issues

**Comment by alyosha-tas** [comment] 2021-01-13 14:13
Cool, @The8bitbeast please test the dev build

**Comment by The8bitbeast** [comment] 2021-01-15 05:20
I had a quick test of the dev build and it feels good. I wont know for sure until I do a long TAS session since desyncs were fairly rare for me, but it sounds and feels like the issue has been dealt with by Alyosha's fix

**Comment by alyosha-tas** [comment] 2021-01-15 14:11
Alright, I'll close this for now then as I can no longer repro. the original issue. Please continue to record your TASing in case anything strange happens again, so far it's the only real lead we've had for all the desyncing issues.

Also note to self: maybe this interaction should be blocked in the other direction as well, frame advance being pressed should prevent new painting, but I don't think it should matter.

**Closed by alyosha-tas** 2021-01-15 14:11 UTC
Labels: App: EmuHawk, Repro: Affects 2.5.2, Repro: Patch Pending, Tool: TAStudio

**Comment by vadosnaprimer** [comment] 2021-01-15 14:29
TAStudio and TASeditor weren't designed with holding advance and rewind in mind, because mouse wheel is the most efficient method, but since people use other methods anyway (hotkeys and GUI buttons), it'd be a good idea to prevent those from colliding with drawing.
