### ISSUE TITLE
Help configuring controllers

### ISSUE THREAD

**Issue by KingDerf** [TASVideos/BizHawk#1103] opened 2018-02-02 19:04 UTC
I'm trying to set up the mac port of bizhawk to play GBA games and I can't get it to recognize any of my controllers. I tried a few usb SNES controllers and for some of them it reads buttons but not dpad inputs and for others it doesn't recognize them at all. I picked up a dualshock 3 today and I have it working in other emulators, but bizhawk also isn't recognizing any of the inputs when i try to configure it.

**Comment by Sappharad** [comment] 2018-02-03 00:04
The old macOS builds of BizHawk are based on an older version of OpenTK where controller support is kind of limited. You can only map buttons and only standard HID controllers are recognized. Rumble isn't supported either. Controllers need to be plugged in before launching BizHawk.

If it doesn't work with your controllers, you're out of luck and need to wait for releases based on 2.0 to be available for macOS. In my case, I have a few older HID controllers (12 or more years old) and those work fine, but I found that newer controllers like the PS4 controller only supported some of the buttons.

These limitations are caused by the controller support in the version of the input library used at that time. They've made improvements since then, which is why you'll need to wait for a version that uses the improvements.

**Comment by YoshiRulz** [comment] 2019-01-29 10:12
Fixed by e483c9449, when #1438 is merged (or clone branch `MoreUnixMonoCompatWork`) you should be good to go on macOS. "Full" macOS support will take a bit longer so expect to put in effort to get it working before then.

**Closed by YoshiRulz** 2019-01-29 10:12 UTC

**Comment by TASblast1993** [comment] 2019-02-04 13:50
Trying to use Switch Gamecube adapter and controllers, but can't even select Controllers in EmuHawk menu.  Help Plz?

**Comment by YoshiRulz** [comment] 2019-02-04 14:10
You can't bind anything to virtual controllers until you've told EmuHawk which controllers are "plugged in". Try this:
1. load a game;
2. go to the core's controller config (e.g. `N64` > `Controller Settings...`) and make sure the controllers you want are enabled; and
3. go to `Config` > `Controllers...` to actually bind them.

Please note this issue is about the macOS port of BizHawk 1.x. If you're still having trouble after following the above, and you're *not* on macOS or *not* using 1.13.2, please open a new issue.

**Comment by TASblast1993** [comment] 2019-02-04 17:33
Using Windows 10 and trying to use Gamecube Controller w/adepter.  Loaded ROM and went to controller config, but don't see a way to select my controller.

**Comment by YoshiRulz** [comment] 2019-02-04 18:24
You don't select a controller, you click in the box and press the button on the controller.

![how2bind](https://i.imgur.com/Ba26LsP.png)

Controllers should be detected as long as you plug them in before opening EmuHawk. My xbone controller was assigned X1 when I took the screenshots.

**Comment by TASblast1993** [comment] 2019-02-04 19:56
Clicked the box, for P1 A Up, and pressed up on gamecube analog stick, but
it didn't work.  I don't know what to say.

**Comment by YoshiRulz** [comment] 2019-02-04 20:19
@TASblast1993 Please [open a new issue](https://github.com/TASVideos/BizHawk/issues/new).
