### ISSUE TITLE
emu.frameadvance() triggers when loading a savestate

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1743] opened 2019-11-27 10:42 UTC
Shouldn't `emu.frameadvance()` trigger only when the core emulates a new frame?
I think that if someone wanted a lua script to advance the main loop when a savestate is loaded, they should instead explicitly using `event.onloadstate(mainroutine)` and `tastudio.onbranchload(mainroutine)`. Otherwise, these two events would have no reason to exist.
What's worse, is that `emu.frameadvance()` is not triggered when you load a TAStudio branch, which results in the script behaving different, depending if you're using TAStudio or not.

**Comment by vadosnaprimer** [comment] 2019-11-27 14:59
`emu.frameadvance()` is you telling the emu to resume emulation. What and how is triggered here?

**Comment by ThunderAxe31** [comment] 2019-11-27 15:06
Example:

    while true do
        console.log("test")	
        emu.frameadvance()
    end

After starting the script above, the string "test" should be printed only after that the core emulated a new frame. However, it will also be printed when you load a savestate, which should not happen. And strangely, it doesn't happen when you load a TAStudio branch.

**Comment by vadosnaprimer** [comment] 2019-11-27 15:07
You're confusing the `while true` loop with `event.onframeend()`.

**Comment by ThunderAxe31** [comment] 2019-11-27 15:08
I'm not confusing anything. I never used event.onframeend() in my life. What I described is what exactly happens when you use the example script.

**Comment by vadosnaprimer** [comment] 2019-11-27 15:10
I'm not saying it doesn't happen, I'm saying you need `event.onframeend()` instead.

**Comment by ThunderAxe31** [comment] 2019-11-27 15:11
All right. Still, I don't see why loading a savestate and loading a TAStudio branch should brought a different outcome, since it makes the script behave differently, depending if you're using TAStudio or not.

**Comment by adelikat** [comment] 2020-04-06 22:47
Fixed it so that tastudio (including branch loading) triggers lua properly (it was always intended to do this behavior but sloppy code)

Closing this ticket since it is now behaving as intended

**Closed by adelikat** 2020-04-06 22:47 UTC
Labels: re: Lua API/scripting
