### ISSUE TITLE
TAStudio often doesn't show latest frames while "Follow cursor" is off

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1943] opened 2020-04-20 23:01 UTC
If you can't see the frames, it's very hard to place inputs on those frames. Quickly toggling "Follow cursor" solves it and shows the otherwise invisible frames. Apparently, according to dart, pausing and unpausing a few times also shows the missing frames.

I've observed this on 2.4, not yet gotten a chance to test the dev builds.

**Comment by RetroEdit** [comment] 2020-04-20 23:33
For future clarification, I will include something adelikat asked and my answer:

> \<adelikat\> RetroEdit, your issue is nonsense
\<adelikat\> follow cursor off = don't show latest frames
\<adelikat\> if you don't like that, don't do it, what do you expect that option to do?

I expect it to load frames up to current playback (in most cases while TASing, you will be playing back *already loaded* frames and refining, not loading new frames). In particular, I think at the very least pausing playback should load all frames up to the current frame. Since it only takes a few seconds to load to the proper frame by doing the "toggle follow cursor" trick, I can't expect a pause-based loading mechanism would be too noticeable for the user anyway.

**Comment by vadosnaprimer** [comment] 2020-04-21 04:55
I don't understand what it means, what tastudio is doing wrong, and what it should be doing. Make a video maybe? If you can't record your talk, type the needed stuff in notepad.

**Comment by adelikat** [comment] 2020-04-24 21:56
The behavior of follow cursor = off is intended.  It isn't about having a performance boost when seeking distant frames, then it is recommended to use the turbo hotkey (shift+tab by default) or toggling throttle.  We don't want it to update on pause/unpause because of the use case.

The reason to have this feature is so that one could use auto-restore, to restore to a frame off screen from the input being edited.  Let's say around frame 100, you were editing a jump, the effects of which were best measured around frame 200.  You don't want to make a single edit and have it start scrolling off screen while you are trying to make another edit.

Closing this because the feature is behaving as intended

**Closed by adelikat** 2020-04-24 21:56 UTC
Labels: Repro: Affects 2.4, Tool: TAStudio
