### ISSUE TITLE
Movie system Id () does not match the currently loaded platform (GEN)

### ISSUE THREAD

**Issue by ItsPietroFelix** [TASVideos/BizHawk#2574] opened 2021-01-16 17:23 UTC
I was making a TAS, and when i clicked to save it, bizhawk crashed and now the .tasproj file doesn't open.
What do I do?

**Comment by ItsPietroFelix** [comment] 2021-01-16 17:23
Version 2.5.2

**Comment by YoshiRulz** [comment] 2021-01-16 17:26
Duplicate of #2479? Using 7zip or similar, remove the file `GreenZone` from the `.tasproj`.

**Comment by ItsPietroFelix** [comment] 2021-01-16 17:40
I tried using WinRAR, but it said that the file was corrupted.

**Comment by vadosnaprimer** [comment] 2021-01-16 17:45
> Using 7zip

Try using 7zip.

**Comment by ItsPietroFelix** [comment] 2021-01-16 17:48
Still nothing.
Guess i'll have to tas it all over again.

**Comment by vadosnaprimer** [comment] 2021-01-16 17:50
Upload it somewhere.

**Comment by ItsPietroFelix** [comment] 2021-01-16 18:01
https://drive.google.com/file/d/1n3ihrH1B6Et15a22dw_Qx1MFJsX-05i8/view?usp=sharing

**Comment by vadosnaprimer** [comment] 2021-01-16 18:04
Try this one https://yadi.sk/d/wMcPXPpBaEfhlA

**Comment by ItsPietroFelix** [comment] 2021-01-16 18:15
Thanks, the file now works!
I think it's case closed now

**Comment by vadosnaprimer** [comment] 2021-01-16 18:16
What version of 7zip do you have?

**Comment by ItsPietroFelix** [comment] 2021-01-16 18:18
9.20

**Closed** 2021-01-16 18:18 UTC
Labels: App: EmuHawk, Repro: Affects 2.5.2, Repro: Fixed/Added in 2.5.3 dev, Tool: TAStudio

**Comment by vadosnaprimer** [comment] 2021-01-16 18:20
Update I guess. I used newer and it worked. Opened, removed `GreenZone`, packages to .zip, renamed to .tasproj.

**Comment by ItsPietroFelix** [comment] 2021-01-16 18:21
Thank you for the help, this TAS was already on the end of the game, and losing 1+ week of work would be awful.
I'll update 7zip.

**Comment by vadosnaprimer** [comment] 2021-01-16 18:22
Don't you have autobackups enabled?

**Comment by ItsPietroFelix** [comment] 2021-01-16 18:23
Yes, they are enabled. But somehow new versions of the file don't show up.
Guess they are set-up to save in the original file, i dunno

**Comment by vadosnaprimer** [comment] 2021-01-16 18:26
Check in `[YourHawkDir]\Movies\backup`

**Comment by ItsPietroFelix** [comment] 2021-01-16 18:27
Nope. Just the "default.tasproj" file there.
Nothing on the file.
