### ISSUE TITLE
"New from Now" in TAStudio doesn't preserve markers

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2366] opened 2020-09-02 12:23 UTC
Simple as the title. I want markers and the marker status (bind to inputs if true) to be preserved when clicking "New from Now" in TAStudio.

*Edit:* It actually retains the marker highlight on the frame number as a visual artifact, just probably not the marker itself in the marker's list.

*Edit 2:* No, this is different than I thought. It does keep the markers, they just don't render properly and some of them are invisible? Not preserving marker's binding status is still an issue.

----

Regrouping, there's two related issues here:

- There's some minor rendering issues, which I really don't care enough about to test again right now, sorry.
- More importantly, the bind markers to input status should be preserved when starting a project "New from Now" (at least, if I didn't botch this issue so much that I'm mistaken about this). So if bind markers to input was set before creating the derived project, it should be set afterwards. Same with it not being set.

**Comment by adelikat** [comment] 2021-01-16 19:23
The only tangible reported issue here "bind markers to input not carrying over" has been fixed since this was reported.  I think it was a general settings bug where this flag wasn't being saved that was fixed in a previous release.

I'm going to close this ticket and if there is a more precise "visual bug" that can be reproduced it should be a new ticket

**Closed by adelikat** 2021-01-16 19:23 UTC
Labels: Enhancement, Tool: TAStudio
