### ISSUE TITLE
PSX BIOS not found by Firmware Manager

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#2346] opened 2020-08-29 20:04 UTC
Manually assigning it will show a checkmark.
```
PSX	U	BIOS (U)	PSX BIOS (Version 2.2 12/04/95 A)	PSX_U.bin	524288	sha1:10155D8D6E6E832D6EA66DB9BC098321FB5E8EBF
```

**Comment by nattthebear** [comment] 2020-08-31 11:23
Duplicate of https://github.com/TASVideos/BizHawk/issues/2224

**Closed by nattthebear** 2020-08-31 11:23 UTC
Labels: App: EmuHawk
