### ISSUE TITLE
gba white screen

### ISSUE THREAD

**Issue by glitchgod010110** [TASVideos/BizHawk#1178] opened 2018-04-15 18:35 UTC
it happens when on TAStudio and going on the power on marker

**Comment by glitchgod010110** [comment] 2018-04-15 18:37
![untitled](https://user-images.githubusercontent.com/38406271/38781923-6a179912-40e4-11e8-917d-01cf4bd15a91.png)

**Comment by alyosha-tas** [comment] 2018-04-15 20:42
This is a duplicate of issue #1001

**Closed by alyosha-tas** 2018-04-15 20:42 UTC
