### ISSUE TITLE
TAStudio takes significantly longer to open

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2278] opened 2020-08-07 14:16 UTC
Opening TAStudio in dev. build takes several seconds (~3 for me) compared to near instantly before ( < 1 second)

**Comment by adelikat** [comment] 2020-08-08 01:02
It looks like it got slower because the new ZwinderStateManager pre-allocates the ram space it intends to use.  And I made those buffers pretty large

**Comment by nattthebear** [comment] 2020-08-08 15:31
> 
> 
> It looks like it got slower because the new ZwinderStateManager pre-allocates the ram space it intends to use. And I made those buffers pretty large

No, `public ZwinderStateManager(ZwinderStateManagerSettings settings)` takes 1-2ms.  The loss is somewhere else

**Comment by adelikat** [comment] 2020-08-08 17:16
The bottleneck was in saving, which has just been fixed by natt, I can confirm it is back to the "usual" load speed

**Closed by adelikat** 2020-08-08 17:16 UTC
Labels: Tool: TAStudio
