### ISSUE TITLE
[melonDS] Window Size option doesn't work

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#1946] opened 2020-04-23 19:03 UTC
All window size options greater than 2x don't work. The only two working are 1x and 2x. I'm using last commit (ebc49db)

**Comment by vadosnaprimer** [comment] 2020-04-23 19:24
Were they working before?

**Comment by YoshiRulz** [comment] 2020-04-23 19:46
Is it only with melonDS? Does NesHawk scale properly?

If so, is this a duplicate of #1927?

---

Off-topic: Maybe we should have a single issue for melonDS problems until next release. It's only been a month (though it sure seems longer) and we're up to 14 already.

**Comment by Real96** [comment] 2020-04-23 19:49
> Were they working before?

They never worked. Just wanted to report it



> Is it only with melonDS? Does NesHawk scale properly?
> 
> If so, is this a duplicate of #1927?
> 
> Off-topic: Maybe we should have a single issue for melonDS problems until next release. It's only been a month (though it sure seems longer) and we're up to 14 already.

Isn't dcale factor is different from window size? (if i'm wrong correct me ofc)

**Comment by vadosnaprimer** [comment] 2020-04-24 12:15
If your monitor is smaller than hawk window resolution you're trying to set, it won't switch to that res.

**Comment by Real96** [comment] 2020-04-24 12:20
I can put the app in full screen and i can manually enlarge the window.
I can't use these options:

![size](https://user-images.githubusercontent.com/20956021/80211867-c209ce80-8636-11ea-8df9-9231c0bd848e.png)

Only 1x and 2x work

**Comment by vadosnaprimer** [comment] 2020-04-24 12:26
Are you saying 3x will be within your monitor resolution?

**Comment by Real96** [comment] 2020-04-24 12:30
I think it should. This is how it look like 2x:

![size](https://user-images.githubusercontent.com/20956021/80212667-35601000-8638-11ea-92a0-1d2a831a277b.png)

**Comment by vadosnaprimer** [comment] 2020-04-24 12:32
Can you also tell the your monitor res while we're being open?

**Comment by Real96** [comment] 2020-04-24 13:05
Monitor resolution is 1920x1080

**Comment by vadosnaprimer** [comment] 2020-04-24 13:23
384*3=1152.

**Closed by vadosnaprimer** 2020-04-24 13:23 UTC
Labels: App: EmuHawk, Core: melonDS, Repro: Affects 2.5 dev
