### ISSUE TITLE
Add ability to swap GB/C cartridges during recording

### ISSUE THREAD

**Issue by greysondn** [TASVideos/BizHawk#1559] opened 2019-05-01 03:07 UTC
Some games go together and have call to swap back and forth while playing in the same recording. Most notable (and the only one coming to mind, honestly) is the Oracle duology of Zelda games on the GBC. Please make it possible to swap them back and forth (as opposed to running two at once) in one recording.

Low level implementation nonsense - power off machine, insert new cartridge, power on machine (basically same as real world). It's expected that an actual save to cart would be required.

Edit: A more casual play of multiple games - Pokemon games, for example - would probably lend itself well to being able to do this, too. From a "ability to record things" standpoint, this makes sense. I don't know that I could justify it from a "what value does this have for tasing" standpoint.

**Comment by hegyak** [comment] 2019-05-01 14:17
I don't quite understand why you want this.  You could do Multi-GameBoy Emulation and record a movie using two separate "player" inputs.

**Comment by greysondn** [comment] 2019-05-01 17:23
Because two gameboys is a noisy mess (unpleasant to listen to, to say the least) and the games are played sequentially with some interaction with the first while going through the second that requires swappping carts back and forth, not simultaneously. Not to mention that with two gameboys there's going to be about six hours of just the title demo playing over and over for the second gameboy. So now you've got a repetitive, noisy, unpleasant mess playing on GB2 so you can finish the game in GB1, Then later (at best) a sitting duck screen on GB2.

May as well ask why we don't have PSX disk swapping require two PSXs and popping the memory card from one to the other.

And Golden Sun can be added to games that this would potentially be useful to play as a duology.

**Comment by hegyak** [comment] 2019-05-01 18:49
PSX games have a function or method where the game explicitly tells you, when your supposed to swap discs.  As far as I am aware, GameBoy does not have this feature.  Which is why I am trying to figure out why this request is being made.

**Comment by greysondn** [comment] 2019-05-01 18:49
So... just in case people haven't played them.

The Oracle games are Ages and Seasons. You can play them in either order, but "officially" they go Seasons and then Ages. Playing them looks something like this.

* Load Seasons.
* Play all of Seasons, save at end of game. The game gives you a password to continue the game into Ages.
* Load Ages
* Start Ages (with password from Seasons).
* Some time into Ages, you'll have someone say "hey, here's a password to give someone in Seasons".
* Load Seasons
* You give that person the password and do a short event (sometimes just a couple lines of dialogue, sometimes a short animation and all). They give you a password to give someone in Ages.
* Load Ages
* You then give that password to the person in Ages, get a small trinket or another small event or some dialogue, and then move on.

The last part of this - swap from ages to Seasons, swap back from Seasons to Ages - goes on a number of times. Like 10 or so times across the game. (And it can be the opposite games in those slots, again, because they can be played in either order. And apparently the events are not entirely the same.) And "small trinket" is a pretty broad word. At least once it's an entire heart container (HP in the game, not an insignificant amount to increase by).

From a production standpoint, having that swap back and forth as one continuous recording makes more sense to me (as it basically forms these little back and forth narratives that are from one side at a time), and from a "I do post-production per-frame" standpoint it removes the need to do cutting up fragments of recordings together with mismatched frame numbers. Everything is one continuous recording and can be played back as such.

**Comment by greysondn** [comment] 2019-05-01 18:56
> PSX games have a function or method where the game explicitly tells you, when your supposed to swap discs.

> As far as I am aware, GameBoy does not have this feature.

I don't disagree. But the generalized case is that "the next piece of the game is on disc so and so". Here, it's the same thing - "the next piece of the game is on cartridge so and so".

It's true (to my knowledge) that the Gameboy doesn't provide for hotswapping. However, as I've detailed in the previous comment, there is at least one circumstance where a company created an example of the general case. That being the passwords in Oracles.

There's also, if memory serves, a long form continuation of narrative between the two Golden Sun games on GBA. There's also, if memory serves, merit to doing a similar sort of long form continuation in the two GBA Metroid games. However, these latter two examples - yet again, if memory serves - require a link cable. Playing them looks much the same - you aren't doing much in the second game until you finish the first, because you need data from the end of the first to transfer into the second.

There may be other games that I simply am unaware of or have forgotten. More fall out of my memory as I keep thinking about it.

**Comment by alyosha-tas** [comment] 2019-05-01 21:32
It's an interesting case. It doesn't fit well with the general architecture of BizHawk but maybe there would be a way to cram it in there. Maybe a long term goal.

**Comment by greysondn** [comment] 2019-05-01 23:38
> It doesn't fit well with the general architecture of BizHawk

This, more than anything, was something that I knew would grind it to a halt no matter how well I could justify the feature.

I have a question: Would it, at the very least, be possible to do one (or more) of the following?

* Mute one of the two emulated handhelds. Post production can do a crop easily enough, but as far as I could tell I was stuck with the game audio from both without independent volume control.

* Blank and/or solo one of the two handhelds. Here, it would be "okay, two are being processed, at a technical level, but only one is being shown to the user".

* Swap controls with a hotkey from "all this, GB1" to "all this, GB2". I think this does exist in TASStudio for tracks per controller and I'm an idiot who never thought they'd have call for it, but I'm uncertain. Forgive me if I've botched that.

There are work arounds for all but the first. For the second (blank/solo) you can use Lua to draw a black over the screen, and it may be possible to crop raw and only show one to client (would have to check). For the third, if nothing else, it's possible (laboriously) to crack open the controller config with emulation paused and swap it over yourself. Obviously neither ideal for ease of use but at least gives some scope of what could conceivably be done by someone who needs it badly enough on their own end.

**Comment by alyosha-tas** [comment] 2019-05-02 00:34
you can turn off volume to one or the other in the gameboy menu. You'll only get mono sound though.

Maybe the second one can be implemented without too much difficulty. 

not sure about the third.

This is a very particular use case though, probably the fastest way to get it implemented is with a PR.

**Comment by greysondn** [comment] 2019-05-02 02:01
As far as myself, I don't know C# or I'd hop right on it and stuff that's even more "well, I needed it, so here it is in a form that may be useful again later".

**Comment by greysondn** [comment] 2019-05-02 02:13
For anyone who comes by via search or curiousity, this much was confirmed.

> you can turn off volume to one or the other in the gameboy menu.

![image](https://user-images.githubusercontent.com/3652901/57053740-f0401280-6c5d-11e9-8e0b-99f9c1b5ef19.png)

I won't pretend to know if there's a unifying GUI layout principle, but I would have expected that in the menu above that, or perhaps in the audio system sliders (Config -> Sound). The tickboxes down there didn't even occur to me because - frankly, I thought that was a line for graphics layers and stuff, basically.

**Comment by ThunderAxe31** [comment] 2019-06-19 17:30
> Because two gameboys is a noisy mess (unpleasant to listen to, to say the least) and the games are played sequentially with some interaction with the first while going through the second that requires swappping carts back and forth, not simultaneously. Not to mention that with two gameboys there's going to be about six hours of just the title demo playing over and over for the second gameboy. So now you've got a repetitive, noisy, unpleasant mess playing on GB2 so you can finish the game in GB1, Then later (at best) a sitting still screen on GB1 while you're playing through the second game on GB2.

I'm very familiar with the Zelda Oracles games, and it seems to me that you have misunderstood about what's the point of the password/link features. These games are designed for having cooperation between two players that play the two titles separately at the same time. Indeed, it's possible to play one of them at time, but since there is no linearity, both games can beat the main story at the same time and then play a newgame+ at the same time. So there is no reason to have one of the two GB to wait in standby for the other one to finish the current game. And even if there happens to be some spare time, that could still be used for farming Rings that could be traded to the other game in order to help.

For the rest, I want to remind that on TASVideos it's not allowed to use passwords that feature arbitrary data, or inputting a password that needs to be displayed by the game first. Luckly, Zelda Oracles games can still start a newgame+ or trade Rings by using Game Link, so the dual GB emulation seems to be the best solution after all. We may still open a topic on TASVideos forums for discussing this further if you want though, as I'm pretty sure that these issues about password usage in general have not thoroughly discussed publicly yet.

> I have a question: Would it, at the very least, be possible to do one (or more) of the following?
> 
> * Mute one of the two emulated handhelds. Post production can do a crop easily enough, but as far as I could tell I was stuck with the game audio from both without independent volume control.

You can't do it for YouTube encodes (afaik) but I'm sure that it could be done for downloadable encodes. A video file can store data for multiple audio tracks, and many popular video players (like VLC) can reproduce both or just one of them on user demand. In any case, the audio part is still just a cosmetic issue.

**Comment by greysondn** [comment] 2019-06-20 19:50
> it seems to me that you have misunderstood about what's the point of the password/link features

No, I'm pretty sure I understand them just fine.

![image](https://user-images.githubusercontent.com/3652901/59876222-02daec00-9371-11e9-881a-20a00ca8c895.png)

Nintendo's marketing is pretty clear that it's one story, not two separate ones to play cooperatively. (Note the choice of words "... which game you play first...")

The resulting mechanics reflect this as well: In order to do Twinrova, you must first beat one game, then play the second using either connection (link cable) with the first or the password system (which will give you a completion code to use to start the second game with).

It's therefore reasonably clear that to do the entirety of the duology you're expected to play one and then the other. The only special quirk is that the order you play them doesn't matter *too much*.

> I want to remind that on TASVideos

It's fair to say that the emulator is targeted to the TAS community and that largely means TASVideos and its standards. It is unfair to assume that we should look at those as limiting potentials as opposed to mandatory "minimum feature" targets. It's also reliably scriptable with a common API for every platform, has a sane format for playbacks, and has useful tools that make it nice for larger projects, unusual applications, and the first part of debugging games. ***I believe BizHawk should always reflect the needs of the TAS community first, but I also believe that it has use outside the TAS community due to overlap in tools.***

> You can't do it for YouTube encodes

I pointed out how to do it in my followup. Those options don't affect sync, so you should be able to change them any time. It appeared to reflect in the output file when I tested it, but I didn't bother much with testing it as I was more concerned about the "playing" part at the time.

**Comment by alyosha-tas** [comment] 2019-12-29 23:27
I just made a commit to GBHawklink which allows selecting which screen (or both) to display. Note that if you change this option while the emulator is paused you will get some garbage displayed since EmuHawk doesn't understand what just happened. But otherwise this works as intended.

Changing carts just isn't going to happen, so I think this is the best I can do for this issue, closing.

**Closed by alyosha-tas** 2019-12-29 23:27 UTC
Labels: App: EmuHawk, Core: GBHawk, Enhancement
