### ISSUE TITLE
BizHawk crashes when starting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#302] opened 2015-06-22 14:36 UTC
```
What steps will reproduce the problem?
1. Download and run installer in bizhawk_prereqs_v1.1.zip
2. Download and extract BizHawk 1.8.4.zip
3. Run EmuHawk.exe


What is the expected output? What do you see instead?
I expect to see the emulator start, but instead I see a Windows error:
Сигнатура проблемы:
  Имя события проблемы:   BEX
  Имя приложения:  EmuHawk.exe
  Версия приложения:    1.8.4.7967
  Отметка времени приложения:   543951c0
  Имя модуля с ошибкой:    StackHash_0a9e
  Версия модуля с ошибкой:  0.0.0.0
  Отметка времени модуля с ошибкой: 00000000
  Смещение исключения:    00000000
  Код исключения:  c0000005
  Данные исключения:    00000008
  Версия ОС:    6.1.7601.2.1.0.256.1
  Код языка:    1049
  Дополнительные сведения 1:  0a9e
  Дополнительные сведения 2:  0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:  0a9e
  Дополнительные сведения 4:  0a9e372d3b4ad19135b953a78882e789

Ознакомьтесь с заявлением о 
конфиденциальности в Интернете:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

Если заявление о конфиденциальности в 
Интернете недоступно, ознакомьтесь с его 
локальным вариантом:
  C:\Windows\system32\ru-RU\erofflps.txt


What version of the product are you using? On what operating system?
I use BizHawk v1.8.4 on Microsoft Windows 7 Ultimate x64

Please provide any additional information below.


```

Original issue reported on code.google.com by `apachaih...@gmail.com` on 30 Oct 2014 at 11:39

**Comment by adelikat** [comment] 2016-11-12 17:57
Closing this ticket either because we have better fallback logic since then, or because it is a duplicate of #392.  I'm going to start lumping all these tickets about not being able to start bizhawk into one to keep the issue tracker tiday

**Closed by adelikat** 2016-11-12 17:57 UTC
Labels: auto-migrated, Core-EmuHawk, Priority-Low, Type-Defect
