### ISSUE TITLE
Trouble with hotkeys

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1780] opened 2020-01-02 20:43 UTC
After the emulator is running for a few minutes, I find the hotkeys no longer work. For instance, the pressing the pause key doesn't pause the emulator. I even rebinded "Ctrl-P" to pause, but I'm also having trouble rebinding hotkeys when the emulator is not processing hotkeys.

I'm using Bizhawk 2.3.2 (x64) on Windows 8.

**Comment by zeromus** [comment] 2020-01-27 06:44
Never heard of this before. Disable "desktop enhancement" software, global hotkey managers, and close steam, and see if any of that helps.

**Comment by RetroEdit** [comment] 2020-01-29 00:33
I don't have any of those running on my PC, to the best of my knowledge. It's a fairly consistent problem, and it has occurred consistently among the most recent three versions (2.3.2, 2.3.3, and 2.4; it might have occurred before that). I would very much like to resolve this as well, so I might compile a debug build so I can see what's up.

The problem with the bug is that I haven't found anything that correlates with it occurring; fortunately, it does usually occur within a reasonable time frame of using the emulator (10-30 minutes), so it hopefully won't be too hard to get more information when I get around to it.

**Comment by zeromus** [comment] 2020-01-29 00:44
The most helpful thing will be to dig deeper into the old versions and find a version where the problem doesn't manifest.

**Comment by RetroEdit** [comment] 2020-01-29 01:15
This only occurred with an old version of BizHawk. I certainly see how malware might be the most plausible explanation, and I perhaps brushed it aside too casually. But it hasn't happened recently (not in the last year, because I haven't used that version of BizHawk), and 

Regarding fixing the malware (or whatever might be causing it) first, what do you suggest I do to fix that? Could mess with virus protection, but I don't generally find that to be particularly productive in solving random non-specific issues, and I generally just let it do its job (or not, as the case may be. :-P). Clean-install would definitely be a hassle, and not sure if that's even possible.

**Comment by zeromus** [comment] 2020-01-29 01:17
Uninstall it and find something else, or use no security software at all. I dunno, if you want security, that's on you. It's not our problem. Any time there's evidence security software is wrecking something, it gets all the blame, and rightly so. I'm sorry you haven't found it productive in solving random issues. I'm certain it's an effective way to solve random issues.

**Comment by RetroEdit** [comment] 2020-01-29 01:26
I think you might be inferring too much from one of my previous comments. I said:

> I suppose it could have been virus protection, but I don't think so...

I don't really think my virus protection was deleting the files. I say this because virus-protection generally informs you when its deleted files (has a list you can check, at least). But I use a different setup now anyway (software-wise; I'm still using the same computer as I was a year ago), so I can still see if the executable-deletion issue still persists when I test some old BizHawk builds.

But I also guess that depends on how plausible any particular explanation of why the executable was deleted is. Is there any probability at all that BizHawk just freaked out and deleted its own executable through some fluke of processing? Or is that just entirely non-plausible (impossible, I doubt, but I'm willing to be convinced otherwise) compared to the explanations of malware or virus-protection?

**Comment by zeromus** [comment] 2020-01-29 02:24
Why don't you leave it to the people who have been supporting and troubleshooting PC software for 30 years or more to decide what it's possible for virus protection to do. Bizhawk did not delete its own executable.

**Comment by adelikat** [comment] 2020-04-12 19:13
The author of this ticket reported that this could not reproduced in 2.4.  Closing

**Closed by adelikat** 2020-04-12 19:13 UTC
Labels: Question/Support
