### ISSUE TITLE
Controller switches to be "X2" after unplugging and replugging

### ISSUE THREAD

**Issue by Gamershy** [TASVideos/BizHawk#2549] opened 2021-01-06 13:38 UTC
I'm quite sure this is an issue with my pc, as opposed to Bizhawk itself, however, this is the last place I can really turn as over 3 hours of searching online have given me no results.
If I reboot my pc with my controller plugged in, it'll register as "X1", which can be presumed to mean "controller 1". However, if I then unplug my controller to use the port for something else, like my phone, or some other device, and then plug my controller back in, it'll register as "X2". This results in the emulator not detecting my input any longer until I reset the controls as the apparent second controller plugged in. This also appears to affect other games in some cases, making the controller entirely unusable in them. I can respect if this is shoved off of here or even deleted, given the nature of it, but I'd presume some other user may have had a similar issue, or even identical issue, and there may be some post somewhere that I am unable to find. If someone can potentially point me in the right direction, or even give me a direct point of help, I'd greatly appreciate it.

**Comment by YoshiRulz** [comment] 2021-01-06 13:43
Duplicate of #2382. I believe there's nothing we can do about this, the input library (OpenTK 3.x) needs fixing or replacing. You may be able to use the workaround of changing `Config` > `Customize...` > `General` > `Input Method` to DirectInput+XInput, as was suggested in that issue.

**Closed by YoshiRulz** 2021-01-06 13:43 UTC
