### ISSUE TITLE
2nd controller input not being detected

### ISSUE THREAD

**Issue by ichikareman2** [TASVideos/BizHawk#668] opened 2016-07-14 08:55 UTC
**What steps will reproduce the problem?**
1. connect 2 controllers to PC. DS4(with a mapper program) or xbox controller.
2. Open psx ROM which enables configuring of controller.
3. Map 2nd connected controller to game controls.

**What is the expected output? What do you see instead?**
Expected: controller buttons are filled up when pressing button from controller.
Actual: controller config does not register the buttons clicked.
*controllers work. checked via joy.cpl

**What version of the product are you using? On what operating system?**
Emuhawk 1.11.6 on Windows 8.1

**Comment by hegyak** [comment] 2016-07-15 01:15
I will look into this when I get a chance.  I don't have two XBox 360 controllers but I do have an arcade stick that works on a 360 and a pad.  I will look into this bug.  See what's going in.

**Comment by hegyak** [comment] 2016-07-30 15:06
I finally got a chance to look into this.  I didn't see any issues assigning buttons to the second player on a secondary XBox 360 controller.  Tested against my Wired XBox 360 Pad, and an Real Arcade Pro XBox 360 Fight stick.  Both controllers were recognized in the Genesis Core.  Which Core(s) did not work?

**Comment by KevinQuingIqmetrix** [comment] 2016-08-02 04:07
In PS1. To be more specific, I was using 2 "Dual Shock 4" (bluetooth connected) and using "Input Mapper" (name of the mapper program). I'll try again when I get home, but I probably won't find anything.

**Comment by zeromus** [comment] 2016-08-02 04:23
I'm skeptical. I've never heard of bizhawk having a problem mapping a 2nd joystick. Maybe "Input Mapper" isn't working properly. We dont use the same interface joy.cpl does; we use dinput and it does not.

**Comment by KevinQuingIqmetrix** [comment] 2016-08-02 05:10
Another point, I tried using DS4windows as mapper as well which resulted the same. I guess I'll try configuring both again and tell you an update.

**Comment by adelikat** [comment] 2016-10-06 19:01
It seems likely that the problem lies with another piece of software (various input mapping apps).  There has not been an update in awhile, so I am closing this issue.

Without using mappers, I am unable to reproduce this problem

**Closed by adelikat** 2016-10-06 19:01 UTC
Labels: bug, OpSys-Any, Priority-Low, Type-Defect
