### ISSUE TITLE
Cheat Dialog Unhandled Exception

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#632] opened 2016-05-21 02:03 UTC
Recreation instructions:
Open a ROM.  I chose Sonic 1 for Genesis.
Attempt to Open the Cheat Dialog.
Error

Error Note:
Error Message Box appears

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: addr
   at BizHawk.Emulation.Common.MemoryDomainIntPtrSwap16.PeekByte(Int64 addr)
   at BizHawk.Emulation.Common.IEmulatorExtensions.Extensions.CanPoke(MemoryDomain d)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BizHawk.Client.EmuHawk.CheatEdit.Restart()
   at BizHawk.Client.EmuHawk.ToolManager.Load[T](String toolPath, Boolean focus)
   at BizHawk.Client.EmuHawk.MainForm.CheatsMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by BooBerry** [comment] 2016-08-07 14:37
I can confirm this, but for me it just straight crashes with a "has stopped working" dialog. Did get this from the log;

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Bizhawk.BizInvokeProxyLibGPGX.gpgx_write_m68k_bus(UInt32 , Byte )
   at BizHawk.Emulation.Common.MemoryDomainDelegate.PokeByte(Int64 addr, Byte val)
   at BizHawk.Emulation.Common.IEmulatorExtensions.Extensions.CanPoke(MemoryDomain d)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BizHawk.Client.EmuHawk.CheatEdit.Restart()
   at BizHawk.Client.EmuHawk.ToolManager.Load[T](String toolPath, Boolean focus)
   at BizHawk.Client.EmuHawk.MainForm.CheatsMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at BizHawk.Client.EmuHawk.MainForm.CheckMessages()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   at BizHawk.Client.EmuHawk.Program.Main(String[] args)

**Comment by adelikat** [comment] 2016-09-27 16:23
Seems to be fixed now

**Closed by adelikat** 2016-09-27 16:23 UTC
