### ISSUE TITLE
SNES: Update Snes9X core to latest.

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2021] opened 2020-05-19 04:53 UTC

**Comment by YoshiRulz** [comment] 2020-05-19 05:13
..? Did you figure out why the sound wasn't smooth?

Edited issue is a duplicate of #1374.

**Comment by Yave-Yu** [comment] 2020-05-19 05:38
> ..? Did you figure out why the sound wasn't smooth?
> 
> Edited issue is a duplicate of #1374.

Sorry for that, because I discovered it's my PC problem, after reboot PC, that issue gone.

**Comment by nattthebear** [comment] 2020-05-19 11:15
Closing in favor of existing issue

**Closed by nattthebear** 2020-05-19 11:15 UTC
