### ISSUE TITLE
Depth Rendering Issue in Banjo Kazooie 1.1 ("Rev A")

### ISSUE THREAD

**Issue by Segmaster** [TASVideos/BizHawk#1445] opened 2019-01-13 06:25 UTC
Noticed an issue that only occurs in when emulating version 1.1 ("Rev A" as Bizhawk calls it) of Banjo Kazooie. Most models and objects have incorrect depth (everything from the N64 logo at the title screen onwards) causing severe graphical glitches and a generally unplayable experience. 

Not sure if this is simply a lack of built-in configuration for this specific release of the game or if there's a more significant problem causing this effect.

Issues persist in both 2.3.1 and 2.2.2 of Bizhawk and GlideN64 video plugin. 
Depth is emulated correctly with Glide64rev2 but it has too many other issues to be usable.

**Comment by YoshiRulz** [comment] 2019-01-13 17:16
Reproducible with 2.3.1 on Win10 *Home* x86_64 1709. The rom in question is [sha1:DED6EE166E740AD1BC810FD678A84B48E245AB80](https://github.com/TASVideos/BizHawk/blob/7ff08fb63e4f96cb55ba4c481d59c2dc0a6fbde9/Assets/gamedb/gamedb_n64.txt#L53), and the setting `GLideN64_CopyColorToRDRAM=2` isn't the cause.

After trying a couple of things I found that by fast-forwarding to the demo gameplay, saving to a slot, then restarting the core and *immediately loading the slot* the depths seemed to be corrected. How long that would have lasted I didn't check. Can confirm that, with default settings + gamedb, neither Glide64mk2 nor Rice exhibit the same behaviour.

Look at this nightmare:
![nightmare](https://i.imgur.com/cKpI0lH.png)

**Comment by zeromus** [comment] 2019-01-14 23:18
I've debugged this at length. there has to be an issue for it already. Everything yoshirulz wrote, I've written before.

**Comment by YoshiRulz** [comment] 2019-01-29 11:08
Resolved by 104e40d8b.

**Comment by YoshiRulz** [comment] 2019-01-29 11:08
Resolved by 104e40d8b.

**Closed by YoshiRulz** 2019-01-29 11:08 UTC
Labels: Core-Mupen64Plus, Repro-2.3.x
