### ISSUE TITLE
Feature Request: add bgb palette for GBHawk

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2488] opened 2020-11-24 16:02 UTC
Currently GBHawk have only 2 palettes in "Non-Sync Settings" → "Color Mode": Gr and BW. It would be great to see BGB palette in GBHawk core in future versions, because for now it is impossible to choose (load) palette like in Gambatte core "GB → Settings → Palette... → Load..." and there bgb palette can be found in Bizhawk\Gameboy\Palettes folder

**Comment by alyosha-tas** [comment] 2020-11-24 16:54
This is a duplicate of #1866 so I'll close this in favor of that one. Not sure if/when I"ll get to it.

**Closed by alyosha-tas** 2020-11-24 16:54 UTC
