### ISSUE TITLE
feature request: gonetz's new glide plugin

### ISSUE THREAD

**Issue by N64Master** [TASVideos/BizHawk#620] opened 2016-04-23 04:06 UTC
gonetz has been working on a new glide 64 plugin ( [https://github.com/gonetz/GLideN64](url) ) which is leaps and bounds ahead of any of the other current plugins. the graphical advancements, whilst large aren't the main reason I would like this feature.

as trialed with mupen, replays recorded with the new glide plugin and played back on others desync after an amount of time, vice versa is true too. from what I can tell, the timing exhibited in the new glide plugin is more accurate to the console itself. it also has progressed significantly for games like pokemon snap which would have otherwise been impossible to tas.

my request is that it be put into bizhawk soon, because the sooner that happens the sooner runs can start syncing with the more accurate timing and hey, they'd look better too

thank you for reading my request and thank you for all the time and effort you've put into bizhawk

**Comment by Isotarge** [comment] 2016-04-23 05:32
Duplicate of #423

**Comment by thecoreyburton** [comment] 2016-04-23 06:43
Isotarge is correct, just under a year ago I posted a request for Gonetz's new GlideN64 video plugin to be included in a future release of Bizhawk and @pjgat09 has been diligently working on it since then, whenever there's time.

This issue should probably be closed, but you're welcome to take your original post and add it to the other issue if you think it's necessary. Rest assured, the development of Bizhawk is very active and it will happen eventually! You can't rush a good thing and the TAS community is one that is admirably dedicated to perfectionism.

**Comment by Isotarge** [comment] 2016-04-23 07:46
Thanks for your interest and enthusiasm. As this ticket is a duplicate I will close it to keep discussion in one place. If you wish to discuss GlideN64 + BizHawk further please use the original ticket.

**Closed by Isotarge** 2016-04-23 07:46 UTC
