### ISSUE TITLE
Incorrect behavior and crash when using event.onmemorywrite() in mGBA core

### ISSUE THREAD

**Issue by Renpona** [TASVideos/BizHawk#2805] opened 2021-06-18 17:53 UTC
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
The Lua event event.onmemorywrite() does not appear to work properly in the mGBA core.

As soon as the event handler is registered, the event starts triggering repeatedly, regardless of whether the memory address is written to. This continues even if the event is unregistered using event.unregisterbyname(). After a few seconds of executing continuously, Bizhawk crashes with an error message, which I've reproduced in the "Output" section.

I originally discovered this issue in Bizhawk 2.6.2, but in order to narrow down the issue, I also tested it in Bizhawk 2.4.2, so that I could try it against the VBA-Next core. When running the test case in that version, the VBA-Next core displayed the correct behavior, but the mGBA core displayed the same issues and crash as it did in 2.6.2.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
This code was written for Final Fantasy V Advance (US), but causes the same issue in other GBA games as well. Any memory address can be substituted for the one given in the example; I tried a number of addresses but did not encounter any change in behavior.
```lua
local function checkBehavior()
	console.log(memory.readbyte(0x020096E0))
	event.unregisterbyname("eventTest")
end

event.onmemorywrite(checkBehavior, 0x020096E0, "eventTest")

while true do
	emu.frameadvance();
end
```

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Emulation.Cores.Nintendo.GBA.MGBAHawk.FrameAdvance(IController controller, Boolean render, Boolean renderSound)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.2; Win10 Home 19042; Intel/NVIDIA, mGBA core
- BizHawk 2.4.2; Win10 Home 19042; Intel/NVIDIA, mGBA core

[//]: # "(screenshots, if applicable)"
*Screenshot*
![image](https://user-images.githubusercontent.com/86124205/122599430-5c4b8380-d03c-11eb-896a-d121dd51358c.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by getCursorsExe** [comment] 2021-06-20 20:37
This probably makes it impossible to TAS Final Fantasy V Advance (US) at this point, if this cannot be fixed in any way, then VBA-Next core needs to be re-added.

**Comment by Real96** [comment] 2021-08-20 22:19
Just tested last commit and got the same issue. It seems that the address is being written every frame

**Comment by getCursorsExe** [comment] 2021-09-19 11:41
Should we waterbox mGBA core or not?

**Comment by getCursorsExe** [comment] 2021-09-19 11:42
Should we waterbox mGBA core now?

**Comment by vadosnaprimer** [comment] 2021-09-19 11:48
> Should we waterbox mGBA core now?

Yes, get on it.

**Comment by InfamousKnight** [comment] 2021-09-19 14:17
> Should we waterbox mGBA core now?

Do you even know what waterbox is? Its just saving the entire core for stable savestates to ensure movies sync. With that said, waterboxing mgba would make no difference here.

**Comment by Renpona** [comment] 2021-09-19 15:31
> Should we waterbox mGBA core now?

That has nothing to do with this issue. Please don't use other people's issues for random unrelated things.

**Comment by CasualPokePlayer** [comment] 2021-09-19 17:21
<https://github.com/TASVideos/BizHawk/pull/2797>
<https://github.com/TASVideos/BizHawk/issues/2585>

Waterboxing would likely make this situation worse at this time, not better.

**Closed** 2021-09-21 12:46 UTC
Labels: Core: mGBA, Repro: Affects 2.4.2, Waiting on Upstream, Repro: Affects 2.6.2

**Comment by YoshiRulz** [comment] 2022-06-04 11:30
Wait is this actually fixed? The repro tool I added seems to work as expected.

**Comment by Real96** [comment] 2022-06-04 11:32
> Wait is this actually fixed? The repro tool I added seems to work as expected.

It has been closed. As far as i've tested it seems to work correctly!

**Comment by CasualPokePlayer** [comment] 2022-06-05 02:41
https://github.com/TASEmulators/BizHawk/issues/3230 was probably the root cause of this bug (the original fix just worked around it).
