### ISSUE TITLE
Fast forward crash (Mega Man X)

### ISSUE THREAD

**Issue by JlNX** [TASVideos/BizHawk#466] opened 2015-07-26 22:43 UTC
![2015-07-26 17_38_35-](https://cloud.githubusercontent.com/assets/13512575/8896327/b2e5e2c0-33bd-11e5-9c96-47080af8bb52.png)
Was playing Mega Man X for SNES, hit the fast forward and got this crash.

**Comment by zeromus** [comment] 2015-07-27 00:50
Which version of bizhawk? Can you reproduce this reliably? Can you reproduce it on other roms? On other consoles?

**Comment by JlNX** [comment] 2015-07-27 14:47
Version 1.11.1
I would say it seems to be sporadic but it does happen on some games more than others.
It happened to me as well on the PSX game Castlevania Chronicles.

**Comment by zeromus** [comment] 2015-07-27 15:46
What kind of CPU do you have? Specific model please

**Comment by JlNX** [comment] 2015-08-08 05:55
![2015-08-08 00_54_39-cpu-z](https://cloud.githubusercontent.com/assets/13512575/9149265/21563cc4-3d68-11e5-85ad-256551eccb58.png)

**Comment by JlNX** [comment] 2015-08-08 22:39
Just adding this one to the mix. I was playing Double Dragon II for the NES and had let it sit and saw the crash.
![2015-08-08 17_37_47-](https://cloud.githubusercontent.com/assets/13512575/9152572/7550945a-3df4-11e5-9e93-253b0842b710.png)

**Comment by zeromus** [comment] 2015-08-08 23:16
Have you changed any state or rewind options from the default settings?  To get the non-delta method in the callstack either the savestate size must be changing (not likely) or you changed the delta compression option. Therefore I cant be sure what settings youre using.

Are you using rewind any when this happens?

I guess I'll have to let the emulator sit overnight and see if it happens

**Comment by JlNX** [comment] 2015-08-12 07:53
Sometime it happens during rewind but these are with out attempting to rewind. Also it does seem like during rewinding some of the states are corrupted. I'll attempt the last post (default and using RAM).

**Comment by JlNX** [comment] 2015-08-12 09:22
I defaulted the settings and it worked. I'm using disk buffer due to RAM being checked before and changed the large states to 30 frames. Thanks for the help.
![2015-08-12 04_21_55-rewind savestate cofiguration](https://cloud.githubusercontent.com/assets/13512575/9220651/b7a19e3c-40a9-11e5-8a1f-b7fc608289e9.png)

**Comment by JlNX** [comment] 2015-08-12 09:24
I backed up the "config.ini" by changing the extension to a ".bak" and let the program create a new "config.ini".

**Comment by JlNX** [comment] 2015-08-12 09:27
I have a notion that backing up the old config file and using a new one once you start using a new revision should prevent a lot of issues.
I'm leaving the thread open so you can see it. Close it whenever you want. Thanks again.

**Comment by zeromus** [comment] 2015-08-12 14:38
There's always a chance that using a new ini file on a new revision can fix bugs, but it's more of something to try when you have trouble instead of something to try every time as a precaution, if you use new builds frequently. 

These savestate & rewind systems are not changing rapidly now. There arent any options that should be causing the problem you were having. Do you have a backup of your old config file? 

Whats your evidence that savestates were corrupted when rewinding? That could be caused by the same problem, really, but I'm curious.

When using a disk buffer, the problem would manifest just as corrupted states. Instead of attempting to illegally expand the memory buffer, the disk buffer would grow to beyond its intended bounds. You could see this happen by checking the size of the tempfile (in %temp%, it's got emuhawk in the name I think) to see if it exceeds 128MB, or maybe in the savestate settings dialog, seeing if it exceeds 100% capacity.

**Comment by zeromus** [comment] 2015-09-01 16:22
I'm gonna close this. If it's a real bug, we'll smoke it out again another day.

**Closed by zeromus** 2015-09-01 16:22 UTC
