### ISSUE TITLE
[TAStudio] ArgumentOutOfRangeException when scrolling in greenzone

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1581] opened 2019-05-29 18:00 UTC
When I'd switch up between two points in green-zone using scroll I got this error:

```
System.ArgumentOutOfRangeException: Value of '8000' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at BizHawk.Client.EmuHawk.TAStudio.<InitializeSeekWorker>b__122_1(Object s, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
```
```
System.ArgumentOutOfRangeException: Value of '147' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at BizHawk.Client.EmuHawk.TAStudio.<InitializeSeekWorker>b__122_1(Object s, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
```

edit: formatting - markdown cheatsheet is [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) --yoshi

**Comment by Croopper** [comment] 2019-05-29 21:31
Got next one :1234: 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '147' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at BizHawk.Client.EmuHawk.TAStudio.<InitializeSeekWorker>b__122_1(Object s, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)

**Comment by Croopper** [comment] 2019-05-29 21:55
This problem shows in your version.
`Next: Value of '6400' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value`
When you change frame.

**Comment by alyosha-tas** [comment] 2019-05-30 21:13
I can't figure out how to reproduce this, can you give more detailed reproduction steps?

**Comment by nlburgin** [comment] 2019-08-28 22:45
This has happened to me a few times, but I have no idea how to reproduce it reliably. 

When I see it, I always save, close bizhawk, and re-open it.

**Comment by nlburgin** [comment] 2019-09-17 21:08
I think I figured out a way to reproduce it reliably.

Open an N64 project in TASTudio, set the greenzone size to 17MB (the lowest possible value) and then try to load a branch.

I think it might be related to a bug in the logic for determining how many states will fit in the greenzone? The settings dialog says the maximum number of states is 2, even though the greenzone is just slightly larger than the size it quotes for *one* state.

**Comment by vadosnaprimer** [comment] 2019-11-23 13:59
> Open an N64 project in TASTudio, set the greenzone size to 17MB (the lowest possible value) and then try to load a branch.

Nope, can't reproduce. Please try from fresh config and list all the steps (or record a video).

**Comment by adelikat** [comment] 2020-05-02 00:17
Closing because we could not reproduce

**Closed by adelikat** 2020-05-02 00:17 UTC
Labels: Repro: Could not reproduce, Tool: TAStudio
