### ISSUE TITLE
Mupen64Plus resets Controllers and Controller addon

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#297] opened 2015-06-22 14:36 UTC
```
What steps will reproduce the problem?
1. Start Super Mario 64
2. Enable all the controllers
3. Set all of the controllers to use Memory Card
4. Reboot core when asked to.
5. Continue to play Super Mario 64.  The title screen is fine.
6. Close EmuHawk.
7. Re-Open EmuHawk
8. Re-Open Super Mario 64
9. Check the Controller settings.

What is the expected output? What do you see instead?
EmuHawk to save the Controller settings.

What version of the product are you using? On what operating system?
r8092

Please provide any additional information below.

```

Original issue reported on code.google.com by `hegyak` on 21 Oct 2014 at 12:42

**Comment by pjgat09** [comment] 2016-09-26 15:58
Does this still happen?

**Comment by adelikat** [comment] 2016-11-12 20:23
I can't reproduce and this sounds like an issue that was fixed a long time ago, closing.

**Closed by adelikat** 2016-11-12 20:23 UTC
Labels: auto-migrated, Core-EmuHawk, Priority-Medium, Type-Defect
