### ISSUE TITLE
TAStudio deletes all branches when loading a .tasproj file

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2658] opened 2021-03-08 16:09 UTC
Version: 2.6.1
Repro:
1. Open a game. Here is the one that I used:
```
    File: Harry Potter and The Sorcerer's Stone (UE) (M12) [!].gba
  CRC-32: f755065c
     MD5: 4eaac54bc741daae77975b004376174f
   SHA-1: 40d3f693e444192c94a0ff3cd9ed5f64162ac777
 SHA-256: 9532eeccbeeb09e36706b53a362239f9db59935799b62d089e93f9d5381058d8
```
2. Launch TAStudio.
3. Create one or more branches.
4. Save the .tasproj file.
5. Load the .tasproj file.
6. There are no branches anymore.

**Comment by YoshiRulz** [comment] 2021-03-08 16:31
Duplicate of #2640.

**Closed by YoshiRulz** 2021-03-08 16:31 UTC
Labels: Repro: Affects 2.6.1, Tool: TAStudio
