### ISSUE TITLE
BizHawk 2.6 causes audio glitches on SNES games (2.5.2 is OK)

### ISSUE THREAD

**Issue by fgimian** [TASVideos/BizHawk#2634] opened 2021-02-21 13:35 UTC
### Summary

Since updating to BizHawk 2.6, the audio on my SNES games are very glitchy (pops and clicks) and seem to be playing at a higher pitch than they should be.  This is with a fresh BizHawk install and no customisation.

Everything seems to work correctly when Speed/Skip is set to **Audio Throttle**, however, this was not necessary in 2.5.2 where Click Throttle worked perfectly.

**Loaded Core**: Snes9x (but also tested and reproduced with the other 2 SNES cores)
**ROM Hash**: Are you after an MD5 checksum or name of the ROM here?  Happy to provide, but I can repro this with multiple different SNES ROMs.
**Video Card (if relevant)**: NVIDIA GTX 1050

### Repro

1. Install BizHawk 2.6
2. Load a SNES ROM
3. Enjoy some audio crackling 😄 
4. Repeat steps 1 - 3 with BizHawk 2.5.2 and note that everything works correctly

### Output

No errors are seen I'm afraid.

### Host env.

- BizHawk 2.6; Win10 Pro 20H2; Intel/NVIDIA

Thanks in advance guys 😄 
Fotis

**Comment by fgimian** [comment] 2021-02-21 13:41
Just tested with nightly build BizHawk_devbuild_13b7b43d via GitLab CI and that appears to work perfectly.  So perhaps I'll just wait for the next release 😄

**Comment by nattthebear** [comment] 2021-02-21 14:14
Duplicate of #2580

**Closed by nattthebear** 2021-02-21 14:14 UTC
