### ISSUE TITLE
Madden NFL 98 and NHL 98 (Sega Genesis) won't work at all

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#1041] opened 2017-10-29 13:48 UTC
Madden NFL 98 just give me a black screen before I can see anything
NHL 98 crash when you are about to select the teams, the same thing happen in NHL 96 but for some reason not NHL 97, which work without problems

- [ ] Madden NFL 98
- [ ] NHL 98

**Comment by zeromus** [comment] 2017-10-29 16:42
test it in retroarch or openemu's gpgx core

**Comment by Tastyfish** [comment] 2017-11-02 01:24
Both games work fine in retroarch's GPGX core, so I assume we're just out of date with upstream.

**Comment by alyosha-tas** [comment] 2018-05-30 01:06
Okay some info on this one (at least for Madden NFL 98)

The game is doing some kind of check by transferring word sized data from unaligned memory.

Part of the problem in recognizing what's happening is that BizHawk incorrectly disassembles the opcode 0108 to BTST instead of MOVEP, even though it's being executed correctly.

So the game uses this opcode to load a bunch of data into RAM (starting at EBB6), from ROM (starting at 204575) then it checks some stuff using that data.

Where things go wrong is that during the time it is loading data, it checks if the data it is pointing at is FF, then stops:

04628C:  0C10  cmpi.b  #$FF, (A0) ... A0:0020466D

That occurs there at 20466D. Then it loops back around to 204575.

The problem is that the checker afterwards has no such bound in place, it keeps checking and only expects to stop at 2046B5. Currently, the value the game is looking for past 20466D is FFB7, it looks for this value in (aligned) memory, but it exists no where in memory so it just loops forever.

But, I don't see any relevent commits in gensplusgx that would fix this, at least not in the cpu core itself, it seems to be doing everything identically to what we have.

I can guess that since the code is loading word sized data from unaligned memory that it should be automatically re-aligned data instead but I don't know for sure. If this were the case, the game would naturally be able to find all the values just by looping back to where it loaded them from in ROM. Not sure what would happen after that.

**Comment by zeromus** [comment] 2018-05-30 01:27
Check for the game accessing something out of range which may return host memory garbage--that would differ between ports of GPGX, even if it was deterministic on ours. 

Manually checking for relevant commits is hard.. if its been a long time, maybe we should just synch with upstream anyway and it will get magically fixed

**Comment by alyosha-tas** [comment] 2018-05-30 02:04
All of this is happening in the standrad ROM and RAM areas of the genesis, so garbage data probably isn't it. Also the exception vector points to code that just tells the CPU to loop forever, so it's definitely not supposed to be throwing that.

Yeah syncing with upstream and it magically working seems like the best bet. I don't know enough about the gensis or the code base to go any further then this.

**Comment by alyosha-tas** [comment] 2018-05-30 12:59
Nevermind all that stuff, it looks like what's happening is that the we are mirroring ROM where we should have SRAM, I'll see if I can fix that.

**Comment by alyosha-tas** [comment] 2018-05-30 20:45
sram.c :

    else if (cart.romsize <= 0x200000)

    {
      /* 64KB static RAM mapped to $200000-$20ffff */
      sram.start = 0x200000;
      sram.end = 0x20ffff;
      sram.on = 1;
    }


Ok I found the problem. this block of code is commented out in our build. I uncommented it and rebuilt in the 1.x branch and this did indeed fix the problem.

I don't know when or why it got commented out, but in gensplusgx master it is indeed active code.

I don't know how much work syncing with upstream would entail, but this is a simple fix for next release if it's not in the works to get done.

@nattthebear any thoughts on this?

**Comment by zeromus** [comment] 2018-05-30 21:55
The comment above it "by default, enable backup RAM for ROM smaller than 2MB" sounds like a bad hack. there's a lot of bad hacks in that vicinity. My guess is, this was breaking some other game. We may have to forward hack flags in from gamedb

**Comment by alyosha-tas** [comment] 2018-05-30 23:07
alternatively we could just add those 2 games to the 'else if' block as in the instances above that code block. Then at least we don't have to inadvertently breaking anything else.

**Comment by nattthebear** [comment] 2018-05-31 11:14
The code does exactly what it looks like it does:  it enables backup ram for EVERY cart of size less than or equal to 2MB.  This is grossly inaccurate.  Many games had no SRAM, and many others had a SRAM much smaller than the 64kB.

https://github.com/TASVideos/BizHawk/commit/28c1347b75e79b602bc09e0e5d926c201d6b439e

Unsurprisingly, it looks like there are some games of that size that do have SRAM but don't get the SRAM detected automatically, and the original GPGX devs elected to avoid the issue and just give them all 64kB.

Especially for TASers, bringing along extra unneeded baggage like this both inflates savestates and can be confusing when doing RAM searches and debugging.  As no one has complained until now, there are probably few affected games and I'd rather special case these known titles than go back to how it was before.

**Comment by nattthebear** [comment] 2020-05-06 21:56
I've started a fix for this in https://github.com/TASVideos/BizHawk/commit/841d5c6857bf

I don't have access to anything that can build the C# side of Bizhawk right now, so it's not complete.  If someone could wire it up and add gamedb entries for whatever EA trash isn't working, that'd be great.

**Closed** 2020-05-09 17:48 UTC
Labels: Core: Genplus-gx

**Comment by nattthebear** [comment] 2020-05-09 17:55
Fixed for the two games outlined in the first post.  Other affected games can be fixed with gamedb entries.
