### ISSUE TITLE
GLideN64 support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#423] opened 2015-06-22 14:38 UTC
```
The new GLideN64 is shaping up to be the most accurate HLE N64 video plugin 
there currently is. Whilst it's not without bugs and there may be later 
updates, it's at public release. Would you be able to include it in Bizhawk?


```

Original issue reported on code.google.com by `video-ga...@pages.plusgoogle.com` on 5 May 2015 at 2:59

**Comment by GamingHD** [comment] 2015-08-03 02:27
When will this be ready for the public? I've seen that it's been included in the project but I'm curious as to when it'll actually be functional.

**Comment by Isotarge** [comment] 2015-09-20 09:21
Any news on this? The DK64 community is waiting for GlideN64 and mupen64plus 2.5 to be rolled into BizHawk to get started on the TAS.

**Comment by GameRecover** [comment] 2015-10-05 13:29
It's not just the DK community, I've got a run planned but I've had it on hold for three months awaiting this. GLideN64 has slightly different timing which causes desyncs on Mupen with most existing runs, so it's likely that it'll have a similar effect in Bizhawk. I'd lose a lot of motivation if I had to restart a run purely for sync, for runs to sync up they'll likely have to use the plugin to begin with.

**Comment by GameRecover** [comment] 2015-10-05 13:29
This also means it's likely that a lot of the current runs won't see better encodes when this is released.

**Comment by TASNinja** [comment] 2015-12-07 16:02
When is this going to be ready? some others people and me have had runs on hold for around a year now. since the new year beta. I'm thinking of abandoning project as I'm running low on free spare time.

What's the date on this? is there progress
The plugin compiles for m64plus is it just a matter of making a gui?

No news since June :( been checking daily since then.

Sorry if message came across rude, pardon my english. Just questions.

**Comment by pjgat09** [comment] 2015-12-07 16:04
I've been busy getting ready for AGDQ 2016. After that I should have time to work on this again.

**Comment by TASNinja** [comment] 2015-12-07 16:25
Thank you for the update :) that is much appreciated as also is your work!
Do you need any help at all?
And when are you expecting this done so I can plan? if you know

**Comment by thecoreyburton** [comment] 2016-02-07 05:16
When this comes out is it going to just be the HLE or is it going to include GLideN64's LLE too?

**Comment by vgturtle127** [comment] 2016-02-07 05:20
@thecoreyburton My guess is not the LLE part, since that is being changed to a different plugin code base, and also will probably receive heavy modifications.

**Comment by thecoreyburton** [comment] 2016-08-19 13:47
Hey, @pjgat09 it's been a while so I thought I'd check in and see if any progress has been made in regards to this.

**Comment by vadosnaprimer** [comment] 2016-08-19 14:46
He's still really busy with tasbot stuff.

**Comment by thecoreyburton** [comment] 2016-08-20 14:45
That's alright! I figured as much which is why I don't check in all that often, but thought I'd ask nonetheless. Thanks for the info!

**Comment by pjgat09** [comment] 2016-09-22 19:19
https://git.io/vidcC
Still needs testing, but it should be functional.

**Comment by thecoreyburton** [comment] 2016-09-24 16:35
As far as I can tell there aren't any visual anomalies different from the plugin's stand-alone branch. I based a lot of my testing around Banjo-Kazooie, however, due to the recently published run.

**Comment by thecoreyburton** [comment] 2016-09-26 05:40
"Use Native Resolution Factor" seems to just set the factor to 1, forcing native resolution only.  You can test this by setting Bizhawk to 1280x960 and enabling that tick box.

On other emulators, there's a slider with multiples so you can play with the game rendering at (for example) 8x native resolution.

**Comment by pjgat09** [comment] 2016-09-26 15:24
Good catch, I changed that setting to a text box defaulting to 0. 

I did some testing with MK64 and found that this plugin is 1 frame behind rice/glide64/glidemk2 and 3 frames behind jabo. I tested that by loading a TAS and single stepping through the beginning of a race and looking at when the timer changed. This results in having more/less input lag, and I'm not sure which plugin is correct.

I tried messing with gliden64 a bit to see if i could reduce that delay, but my attempts didn't seem to have an effect. I would have expected it to at least match rice/glide64, so I'm not sure yet where the problem is.

**Comment by thecoreyburton** [comment] 2016-09-30 04:52
Is the plugin up-to-date with the GLideN64 github page?

Got a bit of an interesting one here. Paper Mario (J) is broken with the GLideN64 plugin in Bizhawk, but not in the latest release of the plugin itself. I haven't had the time to test the other regions, but considering the following:
1) It works inside Bizhawk with other plugins.
2) It's working outside of Bizhawk with the same plugin.

I thought I'd bring it to your attention. The problem occurs during the first minute or so of the intro after starting a new game. Mario and Luigi get a letter and then enter a pipe. Upon exiting the pipe, there are no models or textures other than characters - and shortly after they enter the next area, the graphics plugin freezes completely.

I played around with most of the settings I thought could be responsible but didn't get anywhere. I also included an attached .zip file with both the run from TASVideos and the same run, modified to run with GLideN64 (so if you don't want to go looking for the glitch manually, you can just dial the speed up to get to the glitch in under a minute).

[pm_runs.zip](https://github.com/TASVideos/BizHawk/files/502174/pm_runs.zip)

**Comment by thecoreyburton** [comment] 2016-10-18 13:00
Did a fair bit of testing and interestingly enough the bug isn't present on the interpreter. Guess that particular issue can be chalked up to a core bug.

A few other bits and pieces aren't working correctly (there's a lot of flickering in Lode Runner 3D) but I suspect they're core related too, as the plugin's more thoroughly tested on PJ64 than anything else.

**Comment by adelikat** [comment] 2016-11-12 17:05
I'm going to close this ticket, because the original functionality has been done.  Any GLideN64 bugs (ones specific to bizhawk's porting of it, not the plugin itself) can become new tickets if needed.

**Closed by adelikat** 2016-11-12 17:05 UTC
Labels: auto-migrated, Core-Mupen64Plus, Priority-Medium, Type-Enhancement
