### ISSUE TITLE
N64 - Support Z64 Video plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#193] opened 2015-06-22 14:35 UTC
```
What steps will reproduce the problem?
1. Run Star Wars - Rogue Squadron (U).
2. No gfx displayed.
3.

What is the expected output? What do you see instead?
Expected output is ...beautiful textures.


What version of the product are you using? On what operating system?
SVN r6928 Win8.1 x64 Geforce 750ti Driver 337.88.

Please provide any additional information below.
All 3 video plugins not supported.
Star Wars games and some games need z64 plugins.
Please support it.

https://github.com/mupen64plus/mupen64plus-video-z64/
https://github.com/mupen64plus/mupen64plus-rsp-z64/
```

Original issue reported on code.google.com by `kaito2pr...@gmail.com` on 22 Jun 2014 at 3:09

**Comment by vgturtle127** [comment] 2017-06-04 23:42
@pjgat09 
This is supported by Mupen64Plus, right?

https://github.com/mupen64plus/mupen64plus-video-z64

We just need to hook it up, right?

**Comment by adelikat** [comment] 2017-07-03 21:56
Is there any value to this plugins anymore now that we have GLideN64?

**Comment by thecoreyburton** [comment] 2017-07-06 06:23
As far as I can tell, Star Wars: Rogue Squadron still does not display graphics in Bizhawk even with GLideN64. GLideN64 can get produce different results of different systems though, so this should be verified by someone else as well.

That being said, it is a known issue and regression with GLideN64 as it was working at an earlier point. When using Mupen64Plus, the problem seems to be fixed via toggling to and from fullscreen but the same fix does not appear to work on Bizhawk - so there's probably a discrepancy there. It'll either be fixed in a later version of GLideN64, or potentially might be fixed if/when the N64 core is updated in Bizhawk. 

For now, it might be worth leaving this open to know the problem's still outstanding, but there may be no need for Z64 once this bug is fixed (unless anyone else has a reason or info, of course)!

The issue page is here: https://github.com/gonetz/GLideN64/issues/1459

**Comment by vgturtle127** [comment] 2017-07-16 19:32
@adelikat If we have Glide64, GLideN64, and Angrylion's plugin, that would be all we really need.

**Comment by vgturtle127** [comment] 2017-07-17 21:38
If nobody minds, I would like to close this. Z64 has it's own issues, and I don't think it is better than what we already have, or could have in the future. Glide64, GLideN64, and Angrylion's plugin are really all we need for BizHawk.

**Comment by adelikat** [comment] 2017-11-03 00:29
Fair enough. Closing.

**Closed** 2017-11-03 16:32 UTC
Labels: auto-migrated, Core-Mupen64Plus
