### ISSUE TITLE
Regular Desyncing issues

### ISSUE THREAD

**Issue by LPLibrarian** [TASVideos/BizHawk#2830] opened 2021-07-01 05:35 UTC
Hi all, I've been recording longplays for a while now but lately I've been feeling a bit defeated.

4 longplays in a row have had desyncing issues, a lot of them right near the start of the movie - and I foolishly played through until the end a couple times before finding out.

I've tried what I could find online regarding desyncing issues but I'm still facing the same thing. Using one save state, not altering any settings. The only thing I can note is that since updating Bizhawk it's happened on 3/3 games. Previously it happened much less often - a tolerable amount of errors.

I'm pretty close to losing my cool as one of these games was about 20h of gameplay, and I've only myself to blame for not using due diligence. If anyone could please provide some insight or assistance I'd be really grateful! I don't for the life of me know why it's happening, if it's something I'm doing to cause it, or if there's anything I can do to prevent or minimise it's occurrence. Please excuse my naivety on the technical side of these things, I'll try my best to be helpful. Below is the last game it happened on. Thanks all.

Core: Octoshock (PSX)
Loaded rom's hash: E68B25C0 Scooby-Doo and the Cyber Chase (USA).cue
No open tools or scripts running.
Using BizHawk 2.6.2 on a Win10 Home, Intel(R) Core i7-8750H CPU @ 2.20GHz. 16GB RAM, 64bit OS

**Comment by YoshiRulz** [comment] 2021-07-01 05:41
I'm afraid we have no idea (see the mentioned issue). Anything else you can add might be helpful, such as whether you were using rewind or savestates.

**Comment by zeromus** [comment] 2021-07-01 05:44
PSX is known to be buggy besides whatever else might be going on right now, so rolling back to an older version of bizhawk that's reliable is probably what you want to do

**Comment by LPLibrarian** [comment] 2021-07-01 05:46
Thanks for the prompt response - what a bummer! I typically use up to 3 different save states so I have a point to go back to in case I mess something up. I've tried using less and less and it appears to happen even when using just one save state. No use of rewinds.

I'll try rolling back to older versions. As for the bk2 files I have, is there any way to salvage them? Maybe correct inputs where they start to fail?

**Comment by YoshiRulz** [comment] 2021-07-01 05:47
You can of course do that with TAStudio, but it would be a long, manual process.

**Comment by zeromus** [comment] 2021-07-01 05:48
Yes, it can be done (maybe). You may have to unzip the bk2 and fiddle around with it depending on what versions are involved. of course if you get it to load just replay it til it goes askew and then start recording new input again from there

**Comment by LPLibrarian** [comment] 2021-07-01 05:53
Thanks guys, I'll have a play around with these ideas as well as rolling back and see how we go.

**Comment by alyosha-tas** [comment] 2021-07-01 21:41
If you are going to use older builds, keep in mind that using autofire will cause desyncs in builds back to and including 2.5, so don't use autofire in these builds if you want to maximize your sync chances.

**Comment by LPLibrarian** [comment] 2021-07-02 01:18
Great tip, appreciate the heads up!

**Comment by Zimond47** [comment] 2021-07-06 15:57
I might have more info. I had the same problem with PSX and tested a little. It seems to be an issue with increasing the speed during playback. On 100% speed the TAS runs fine but if you increase the speed the framecounter speed doesnt change. So while the game runs at like 180fps for example the framecounter is still running at 60fps.

**Comment by Zimond47** [comment] 2021-07-06 16:17
![psxunthrottled](https://user-images.githubusercontent.com/57569506/124634131-47694f80-de86-11eb-9bda-d80e1b5a9991.jpg)
Left 2.6.2 Right 2.5.2
Both started almost in the same time and unthrottled.

**Comment by zeromus** [comment] 2021-07-06 16:45
are you telling me you have a tas that will run fine at 60fps but if fast-forwarded or unthrottled, it will desync?

**Comment by Zimond47** [comment] 2021-07-06 17:31
Yes. 
It's not just a desync. The speed of the TAS is not locked to the game speed when you unthrottle the speed in 2.6.2 
So when the game runs for approx 180fps in this example only 60fps of inputs are recorded when you record unthrottled. 

Same when you play it back and then throttle it. See the screenshot, you can reproduce this.

**Comment by zeromus** [comment] 2021-07-06 18:11
are you telling me you have a tas you recorded at 180fps, but if played back at 60 fps it will desync?

**Comment by Zimond47** [comment] 2021-07-06 19:36
No, of course not. It was just an example. It's just that when ever you unthrottle the speed (for example rush through a boring scene you still dont want to cut) At this point the TAS is screwed since the input recording is still running at the same speed. 

You can easily reproduce this.
Open a PSX game.
Open the tasstudio.
Unthrottle the speed.
Let it run for a minute.

The framecounter should be at a multiple of 3600, depending on the speed the core is running on your system. But it's not. It will be 3600 no matter how fast the emulation runs.

**Comment by nattthebear** [comment] 2021-07-06 23:02
Cannot reproduce.  Opened a PSX game, opened tasstudio, turned off all throttles, started emulation, stopwatched for about one minute, stopped emulation, and frame counter was at 5500.

**Comment by YoshiRulz** [comment] 2021-07-06 23:18
"Unthrottled" is a separate menu item and not equivalent to disabling "Clock Throttle" — which were you testing with?

**Comment by nattthebear** [comment] 2021-07-06 23:48
I guess I was on "Throttled: None"; why is that a separate thing than "Unthrottled: None"?

**Comment by LPLibrarian** [comment] 2021-07-06 23:52
> I might have more info. I had the same problem with PSX and tested a little. It seems to be an issue with increasing the speed during playback. On 100% speed the TAS runs fine but if you increase the speed the framecounter speed doesnt change. So while the game runs at like 180fps for example the framecounter is still running at 60fps.
> 
> Edit : This only happens with the "unthrottled" option not with increasing the speed in steps. So :
> Increase/Decrease Speed accordingly alter the framecounter speed... Toogle throttle does not
> Edit 2: This is also the case when recording and toggle the throttle. Input recording stays at about 60fps while the game runs 2-3x.
> @LPLibrarian : Worth a try. If you have not touched the throttle during recording but only for playback maybe some of your files can be used after all by playing them in normal speed?

Great work following this up @Zimond47 - I was hopeful as I do typically mess with speeds, however this didn't salvage my files. Hopefully and surely this will help others at the very least!

**Comment by Zimond47** [comment] 2021-07-07 00:05
Just to clarify, I was using the hotkey for "Toggle Throttle". I have that mapped on the gamepad

**Comment by alyosha-tas** [comment] 2021-07-07 14:27
Please try dev build as of most recent commit, I might have introduced this problem when fixing the autofire one (definitely a bug either way.)

**Comment by Zimond47** [comment] 2021-07-07 19:55
Can confirm. This fixed it. Test recorded for 3 minutes and played around with the throttle a lot... all fine now. Thank you very much 👍

**Comment by alyosha-tas** [comment] 2021-07-07 20:52
Cool, @LPLibrarian please try to record something using your usual workflow in dev. build and see if it syncs.

**Comment by alyosha-tas** [comment] 2021-07-25 13:55
Closing as the identified problem is fixed. @LPLibrarian if you still encounter desyncs please open a new issue with fresh info.

**Closed by alyosha-tas** 2021-07-25 13:55 UTC
Labels: App: EmuHawk, Core: Octoshock, Repro: Affects 2.6.2, Repro: Patch Pending
