### ISSUE TITLE
Controller can't be detected after program starts

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2140] opened 2020-06-16 16:55 UTC
This is a tiny annoyance: if I start BizHawk, but then try to plug in my USB controller afterwards, BizHawk doesn't detect my USB controller. Thus, I have to entirely close and reopen BizHawk to actually play with my controller. This may be only me; I can provide further details about my controller if needed.

**Comment by YoshiRulz** [comment] 2020-06-16 16:57
Can you do regression tests on releases from 2.3.2?

**Comment by RetroEdit** [comment] 2020-06-16 18:01
As a start, 2.3.2 works, but 2.3.3 and 2.4 are broken. This at least confirms it's a regression (which I didn't realize), though I can imagine that might not be specific enough to be actionable.

**Comment by adelikat** [comment] 2020-06-16 18:02
I think it was a dinput specific implementation, then we defaulted away from dinput, if I were to guess

**Comment by dart193** [comment] 2020-06-20 21:03
I have noted this issue on 2.4.2 when I wiped my settings and controller scheme switched from DInput. I do not remember any issues on 2.3.2, but I remember my controller being detected as "X1". On 2.4.2 with DInput, it is either J1 or J65535, depending in Windows mood, so I need to use another setting for it to be X1... which requires plugging gamepad before starting emulator.

What bogs me is that I am not sure that I used DInput since how exactly it detected the gamepad as X1? it is something that XInput does. Yet with the setting that allows this, hot plug does not works.

This issue can be temporarily "worked around" by save stating, restarting the emulator and then load stating without any loss, but this is cumbersome. I agree that some better fix is needed. If constant detection is not possible, can you add "Refresh input devices" button into config menu which will reinitialize input devices?

**Comment by YoshiRulz** [comment] 2021-01-17 18:18
Not sure if this was only an issue with OpenTK with DirectInput as well, but the former is beyond a doubt fixed as of e71506ac6 (2.6 release).

**Closed by YoshiRulz** 2021-01-17 18:18 UTC
Labels: App: EmuHawk, Repro: Affects 2.4, Repro: Regression from 2.3.2
