### ISSUE TITLE
GBC - Poyon no Dungeon room not working in SGB

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2421] opened 2020-09-23 19:51 UTC
After hudson soft logo games is stuck on white screen. Also changing core from BSNES to SameBoy and from SameBoy to BSNES gives no effect. Record video also attached to this issue.

[Poyon no Dungeon Room.zip](https://github.com/TASVideos/BizHawk/files/5271512/Poyon.no.Dungeon.Room.zip)

Happens on Bizhawk 2.5.1 and Developer build, rom is marked green ✓

(Bizhawk 2.4.2 - working fine in SGB -- SameBoy core)

**Comment by nattthebear** [comment] 2020-09-23 19:53
Super Gameboy cannot run games that are only for the Gameboy Color.  This is how it worked on real hardware.

**Comment by YoshiRulz** [comment] 2020-09-23 19:54
The core should throw an exception for RomLoader to catch, then.

**Comment by zeromus** [comment] 2020-09-23 19:59
maybe, maybe not. depends on 
1. matter of opinion
2. how/whether the detection of this condition is reliable

In any event this is a feature request "friendly tip that chosen combination of game and core yields most likely undesirable result"

**Comment by nattthebear** [comment] 2020-09-23 20:19
There are games that function fully with enhancements on GB, SGB, and CGB.  I don't know if there's a header or heuristic that would work for this.

**Comment by zeromus** [comment] 2020-09-23 20:40
Then I'd say close it again, we're not gonna add junk to the gamedb just to advise users that theyve chosen something suboptimal. Otherwise we will have to add a flag for games that suck and warn users about that too.

**Comment by medigi** [comment] 2020-09-23 20:59
Before closing issue, i just checked this game on Bizhawk 2.4.2 and it works fine there in SGB mode.

**Comment by RetroEdit** [comment] 2020-09-23 21:56
In that video you provided, the bsnes core was active, and evidently bsnes has a problem emulating SGB with that game.

So the issue is not about emulation changing (because the cores themselves haven't changed), but it's that SameBoy crashes for some reason and the fallback is bsnes.

This is not specific to this particular game, I don't think; I also tried Donkey Kong Land 2, and it also fell back to bsnes. So SameBoy's calling code probably broke and started throwing exceptions in 2.5 for some reason.

**Comment by nattthebear** [comment] 2020-09-23 22:51
OK, I dug into this some more.  This game, regardless of what certain groups may label it as, in fact fully supports running on GB mono, GB color, and GB super, and has enhancements for both color and super.  It doesn't work in BSNES because of some mapper bullshit.  It doesn't work in 2.5.something Sameboy because the picker is broken and Sameboy is never selected.  #2422 will fix this.

**Closed** 2020-09-24 13:23 UTC
Labels: App: EmuHawk, Core: Sameboy, Repro: Affects 2.5.1, Repro: Regression from 2.4.2
