### ISSUE TITLE
Add hot-key to menu in cheats window

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1576] opened 2019-05-29 03:24 UTC
I suggest to add this option in that way:
![cheats_hotkey_menuv3](https://user-images.githubusercontent.com/49565819/58527067-bb719d80-81c0-11e9-8ba2-aa649d51c6bd.png)

Believe me this option will be very useful.

**Comment by zeromus** [comment] 2019-05-29 03:30
Would almost certainly be easier to add 10 blank hotkeys called "Cheat 0" and "Cheat 1" for example, then let you pick which of those cheat hotkeys to use for a cheat: "Hot-key: Cheat [0,1,2,3]" where the dropdown lets you choose only 0,1,2,3,etc

**Comment by YoshiRulz** [comment] 2019-05-29 03:52
Duplicate of #553.

**Closed by YoshiRulz** 2019-05-29 03:52 UTC
Labels: App-EmuHawk
