### ISSUE TITLE
Pokemon crystal

### ISSUE THREAD

**Issue by garterser** [TASVideos/BizHawk#2617] opened 2021-02-10 19:48 UTC
when i open pokemon crystal i get this error message, i think it's reading it as a archive?

![10 02 2021_13 44 57_REC](https://user-images.githubusercontent.com/78876942/107563394-a3b19700-6ba6-11eb-9902-add52d616d62.png)

**Comment by TiKevin83** [comment] 2021-02-10 19:51
duplicate of #2587

**Comment by zeromus** [comment] 2021-02-10 19:51
use recent buildbot build

**Closed by zeromus** 2021-02-10 19:51 UTC
