### ISSUE TITLE
Lua script restarts when calling emu.frameadvance() in while loop

### ISSUE THREAD

**Issue by coderesting** [TASVideos/BizHawk#1516] opened 2019-03-19 14:38 UTC
When you open a rom file with Lua and then use `emu.frameadvance()` in a while loop the script restarts repeatedly. I used Super Mario Kart and the Snes9x core.

Here my examplescript to reproduce.
```
console.log('starting')
client.openrom('rompath.smc')
while true do
  emu.frameadvance()
end
```

The output in the console is repeatedly 'starting'.

**Comment by Ashafix** [comment] 2019-03-23 20:02
Hm, tried reproducing it but couldn't. In my case the ROM couldn't even be loaded via a Lua script.

Perhaps related to #1140 and #1141?

@yannickbrandt : Via the command line you can load the ROM and execute the LUA script.

e.g.
emuhawk.exe --lua=yourLua.script rompath.smc

**Comment by YoshiRulz** [comment] 2019-03-24 03:39
@Ashafix I had to set the ROM path in `Config` > `Paths...` first, then use a relative filename.

**Comment by yannickbrandt** [comment] 2019-03-24 16:07
@Ashafix Yes it works for me when i open the rom from cli. I just didn't think about that.

**Comment by Gikkman** [comment] 2019-03-30 20:37
I've been tinkering with this same thing, and just can't get it to work. My main goal would be to load files using absolute paths, which so far hasn't worked. I tried relative paths too, but I can't get that to work either.

In a perfect world, this would work:
```
print("load")
client.openrom("C:\Games\SOS(USA).sfc")
while 1 do
        print("running")
	emu.frameadvance()
end
```
From my experience, it just prints `load` once and then keeps spamming `running`, but no game runs. It is mentioned that this shouldn't work in #1141 though.

**Comment by vadosnaprimer** [comment] 2019-06-08 21:22
What's the current problem in a nutshell?

**Comment by YoshiRulz** [comment] 2019-06-09 03:35
I think this is because Lua scripts restart when a core/rom is loaded. The client needs to remember if a load was caused by `client.openrom` and ignore the same `client.openrom` call somehow.

**Comment by vadosnaprimer** [comment] 2019-06-09 05:31
Duplicate of #1141 then. And I like having this lua condition in preventing endless reloads, because it has to be explicitly prevented. To properly fix it there'd need to be a boolean passed all the way to https://github.com/TASVideos/BizHawk/blob/master/BizHawk.Client.EmuHawk/tools/ToolManager.cs#L508 along the lines of `FromLua`.

**Closed** 2019-06-09 05:37 UTC
Labels: Repro-2.3.x, Topic-Lua
