### ISSUE TITLE
Fatal error: SEHException in BizHawk 2.5.1 when using BSNES

### ISSUE THREAD

**Issue by Morilli** [TASVideos/BizHawk#2395] opened 2020-09-14 04:29 UTC
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Trying to seek around in a .bk2 file made from an earlier version of BizHawk (precisely 2.4.0) crashes bizhawk consistently with varying messages depending on what you do exactly, I've gotten at least 3 different variants so far.

### Repro
Open [this .bk2 file](https://github.com/TASVideos/BizHawk/files/5216086/Akogare.Mario.World.any.v1.21.bk2.zip) in TAStudio (Note: I'm using [this rom](https://drive.google.com/drive/folders/1vSeC2IKs1ilh8mYnm6Z9CGCk01y7n451) patched on vanilla super mario world.
1. Click on frame 10,000 or at some other frame (it really doesn't matter) so that it starts seeking or playing.
2. Pause
3. Click on frame 0 or any other frame that has been played, really shouldn't matter.
4. enjoy

It should honestly be super easy to crash bizhawk this way, for me it has even worked to advance one frame and then go back one frame for bizhawk to crash immediately.

### Output
![screencap](https://cdn.discordapp.com/attachments/541378030635974696/754915226435977230/unknown.png)
have gotten an InvalidOperationException and some stacktrace in another instance too; don't have screenshot of the stacktrace tho.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.1; Win10 Pro 2004 build 20211

edit: screencap link -> embed --yoshi

**Comment by nattthebear** [comment] 2020-09-14 11:23
What emulation core is being used?

**Comment by YoshiRulz** [comment] 2020-09-25 00:28
The screencap seems to be an `SEHException` which would be from Rust, but an `InvalidOperationException` from TAStudio looks like the bug fixed by 757ac4e27. Can you reproduce any crash on a dev build from today?

**Comment by Morilli** [comment] 2020-09-25 05:17
Well I'm not managing to reproduce this consistently currently, but I did manage to reproduce this error, and this time even with a stack trace!

```

************** Ausnahmetext **************
System.Runtime.InteropServices.SEHException (0x80004005): Eine externe Komponente hat eine Ausnahme ausgelöst.
   bei Bizhawk.BizInvokeProxyWaterboxHostNative.wbx_load_state(IntPtr , ReadCallback , IntPtr , ReturnData )
   bei BizHawk.Emulation.Cores.Waterbox.WaterboxHost.LoadStateBinary(BinaryReader br) in D:\GitHub\BizHawk\src\BizHawk.Emulation.Cores\Waterbox\WaterboxHost.cs:Zeile 307.
   bei BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore.LoadStateBinary(BinaryReader reader) in D:\GitHub\BizHawk\src\BizHawk.Emulation.Cores\Consoles\Nintendo\SNES\LibsnesCore.IStatable.cs:Zeile 18.
   bei BizHawk.Client.EmuHawk.TAStudio.LoadState(KeyValuePair`2 state)
   bei BizHawk.Client.EmuHawk.TAStudio.StartAtNearestFrameAndEmulate(Int32 frame, Boolean fromLua, Boolean fromRewinding)
   bei BizHawk.Client.EmuHawk.TAStudio.GoToFrame(Int32 frame, Boolean fromLua, Boolean fromRewinding)
   bei BizHawk.Client.EmuHawk.TAStudio.TasView_MouseDown(Object sender, MouseEventArgs e)
   bei System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   bei BizHawk.Client.EmuHawk.InputRoll.OnMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Guess this is just the classic part where it tries to load a savestate that doesn't exist and just throws in some way.

Note that when bizhawk crashes immediately by doing frame advance + going one frame back, this seems to be the line that fails it: https://github.com/TASVideos/BizHawk/blob/afbce436cd5805395ddaa6eecbb91f7b60842347/waterbox/waterboxhost/src/memory_block/mod.rs#L946

**Comment by zeromus** [comment] 2020-09-25 06:48
Have you edited the bk2 by hand (treating it as a zipfile) to remove the greenzone file?

**Comment by Morilli** [comment] 2020-09-25 07:02
The .bk2 doesn't contain any greenzone, so no.

**Comment by YoshiRulz** [comment] 2020-09-29 04:33
Two other users reported an `SEHException` when seeking to frame 0 with TAStudio. Both were using BSNES. I tried to repro but couldn't, will try again on Windows.

**Comment by RetroEdit** [comment] 2020-09-30 14:37
I was able to reproduce easily on Windows. Saving and then loading a state seems to be broken. You don't need TAStudio open.

**Comment by nattthebear** [comment] 2020-09-30 14:40
Anyone able to reproduce this on linux?

**Comment by Morilli** [comment] 2020-09-30 17:30
I tried to test this by using WSL, but it seems there are lots of issues in the linux version, starting with the BSNES core not even working at all, so I cannot test this right now.

**Comment by nattthebear** [comment] 2020-09-30 17:41
Huh, bsnses worked in linux last I checked?

**Comment by Morilli** [comment] 2020-09-30 17:48
Yeah this might very well all be due to me using WSL2 instead of a real linux system; I just know it's throwing tons of errors and not really working at all.

**Comment by YoshiRulz** [comment] 2020-09-30 18:32
Still cannot repro on Linux with RetroEdit's more detailed steps.

**Comment by nattthebear** [comment] 2020-09-30 19:18
All of my linux work has been WSL2, but anyway that's orthogonal to this issue here.  Seems like it's broken on W10 and working on linux (so long as you can get the hawk itself working on linux to start.)

This is not unexpected as there's a difference to how the waterboxhost handles certain BSNES things on windows and linux.

**Comment by nattthebear** [comment] 2020-10-12 18:00
@RetroEdit Could you test c86f1e1e98d1c3c45ec99cd0d2f38324db0fa3de and see if the issue still exists?
@YoshiRulz Could you do a light regression on bsnes stateing with c86f1e1e98d1c3c45ec99cd0d2f38324db0fa3de?  I doubt anything broke, but it's nice to be sure.

**Comment by YoshiRulz** [comment] 2020-10-12 18:37
Wasn't able to get a crash with the branch.

**Comment by Morilli** [comment] 2020-10-12 21:10
With short testing, I couldn't get a crash on that commit anymore. Seems to have fixed the issue.

**Comment by nattthebear** [comment] 2020-10-13 13:11
Incorporated into master as 98ad14ff47a0206756f01f4afbe6ae539a612582

**Closed by nattthebear** 2020-10-13 13:11 UTC
Labels: Core: BSNES, Repro: Affects 2.5.1, Repro: Fixed/Added in Branch/Fork, Repro: Regression from 2.4.2
