### ISSUE TITLE
Update SNES9x Core to latest master? Lots of updates

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1722] opened 2019-11-07 12:44 UTC
Update SNES9x Core to latest master? Lots of updates since what is in bizhawk.

Please? :)

**Comment by YoshiRulz** [comment] 2019-11-07 12:48
Duplicate of #1374 (which you opened).

**Closed by YoshiRulz** 2019-11-07 12:48 UTC

**Comment by jjfmz42015** [comment] 2019-11-07 13:04
sorry forgot I opened that.

I just thought ide ask in case it was easy.


I can use BSNES.
