### ISSUE TITLE
[melonDS] Major sync issue

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1911] opened 2020-04-05 09:54 UTC
I've already found a major sync instability issue. Download and play back this movie file: http://dehacked.2y.net/microstorage.php/get/737638915/Pokemon%20Mystery%20Dungeon%20-%20Blue%20Rescue%20Team%20%28USA%29.bk2

Emulator version:
BizHawk_Developer-2020-04-03-230826-#96a753324ada6486d0ec1dd978d0c54e1555a68b

ROM checksum (No-Intro):
```
    File: Pokemon Mystery Dungeon - Blue Rescue Team (USA).nds
  CRC-32: b6c4143e
     MD5: 61373235da72064e8c058fae3c646916
   SHA-1: 503edef4fe6088bca00616efcac3b13da90cd105
 SHA-256: 4bdf72ce0dd7a19c66f49e840f046124994d719678e88a0814d0148f705d3e8b
```

Around frame 640, you will see a Pokémon walking from below towards up. The issue is that each time you play back the movie, a different Pokémon will appear! This obviously shouldn't happen in a deterministic environment. Note that DeSmuME doesn't have this issue, as it always spawns the same Pokémon ([Eevee](https://www.spriters-resource.com/game_boy_advance/pokemonmysterydungeonredrescueteam/sheet/52336/)) when it starts from clean SRAM.

**Comment by vadosnaprimer** [comment] 2020-04-05 15:06
Does this core have a trace logger or disasm of some kind?

**Comment by SuuperW** [comment] 2020-04-13 21:24
If you start the movie and create a savestate at frame 0, then load and play from there multiple times, do you always get the same Pokemon?
If no, it's not an issue with any BizHawk-related code. I likely will eventually look into this, but at the moment wouldn't know where to look.
If yes: if you reboot/restart the movie (such that a different Pokemon will appear), but then load that same savestate you created earlier, do you get the original Pokemon or a new one?

**Comment by InfamousKnight** [comment] 2020-04-24 00:13
Because there was no response from the OP, I tested it myself.

The first answer, yes and no. The one that was there originally before the movie was written was different from the one if I loaded a save state on playing back. If I load the save state multiple times, the same one appears(yes, I did make a save state at frame 0 just to be clear). So yes and no.

**Comment by ThunderAxe31** [comment] 2020-04-29 11:15
Sorry for not testing it myself, but I wanted to wait for the [core regression](https://github.com/TASVideos/BizHawk/issues/1963) to be fixed, before looking into this further.
By the way, I also wondered if it could be caused by bad RTA management, but since I've noticed that the Pokémon species changing were more or less the same in each try. It looked like a timer started from the moment the core is started, however it didn't seem to get resetted by rebooting the core, but only by reopening BizHawk.
I apologize for not giving objective data, but maybe it could still give an idea about where to start looking.

**Comment by SuuperW** [comment] 2020-04-30 08:57
I tested RNG with another game, and found that it is inconsistent because MelonDS assigns itself a random MAC address. If I always use the same MAC address, the RNG is consistent.
I'll push updates hopefully later today.

**Comment by ThunderAxe31** [comment] 2020-04-30 12:02
Then it's probably related to this: https://github.com/Arisotura/melonDS/issues/443

**Comment by InfamousKnight** [comment] 2020-04-30 12:49
Looks like someone already fixed it: https://github.com/Arisotura/melonDS/pull/579 we just need to integrate that into bizhawk.

**Comment by SuuperW** [comment] 2020-04-30 22:21
The mentioned fix isn't merged into melonDS yet, so I'll wait until that happens then update here.

**Comment by SuuperW** [comment] 2020-05-02 09:29
I just realized that the mentioned PR is a few months old. And from the latest comment there, it could be a while before that feature is officially part of MelonDS. So I'll just quickly set a hard-coded MAC address for now.

**Comment by InfamousKnight** [comment] 2020-05-02 12:09
Sounds good to me :)

**Comment by SuuperW** [comment] 2020-05-02 13:54
Commit ac2d5d7 fixes the MAC address.
Please verify that the issue is solved, just in case there's something more going on with that movie/game.

**Comment by InfamousKnight** [comment] 2020-05-02 15:24
It works! Recorded a movie, got Eevee, stopped movie. Played it back multiple times, got Eevee. Woohoo!

**Comment by ThunderAxe31** [comment] 2020-05-02 16:02
> It works! Recorded a movie, got Eevee, stopped movie. Played it back multiple times, got Eevee. Woohoo!

@InfamousKnight I got Torcic. I hope that's because of different sync settings or different firmware.bin
Please try playing back my movie file yourself: http://tasvideos.org/userfiles/info/63076822060140049

**Comment by InfamousKnight** [comment] 2020-05-02 17:12
I cant right now as I have to work. I didnt touch any sync settings nor did
I use firmware. I just used the incomplete hle bios. In other words, you
dont need any firmware put in for it.

**Comment by SuuperW** [comment] 2020-05-02 20:54
Awesome.
Behavior is expected to differ between using bios files and not, especially where timing-based RNG is involved.

**Closed by SuuperW** 2020-05-02 20:54 UTC
Labels: Core: melonDS, Repro: Affects 2.4.1 dev
