### ISSUE TITLE
[SMSHawk] Small collection of bugged games in 2.3

### ISSUE THREAD

**Issue by synnae** [TASVideos/BizHawk#1323] opened 2018-09-13 22:38 UTC
Here are all of the version 2.3 bugged SMS/GG games I know (that apparently weren't reported yet):

**Argos no Juujiken (SMS)**
D-Pad doesn't work, making it impossible to move the character.

**Double Target - Cynthia no Nemuri (SMS)**
Glitched graphics.
![double target - cynthia no nemuri j](https://user-images.githubusercontent.com/24638400/45517247-e5df1000-b783-11e8-895c-df13da8547be.png)

**Kujaku Ou (SMS)**
Glitched graphics.
![kujakuou j](https://user-images.githubusercontent.com/24638400/45517285-014a1b00-b784-11e8-9824-f274b6c761c8.png)

**The Ninja (SMS)**
Glitched graphics.
![the ninja j](https://user-images.githubusercontent.com/24638400/45517291-073ffc00-b784-11e8-834a-71aec3470243.png)

**Zillion (SMS)**
Glitched graphics.
![zillion je en ja](https://user-images.githubusercontent.com/24638400/45517301-0e670a00-b784-11e8-9a7a-ea403d1717ff.png)

**Master of Darkness / In the Wake of Vampire (GG)**
Audio plays much faster than it should. Here's a comparison between it and the SMS version of the game:

[In the Wake of Vampire Audio (GG).zip](https://github.com/TASVideos/BizHawk/files/2381072/In.the.Wake.of.Vampire.Audio.GG.zip)

[In the Wake of Vampire Audio (SMS).zip](https://github.com/TASVideos/BizHawk/files/2381077/In.the.Wake.of.Vampire.Audio.SMS.zip)

Above is the Stage 1 theme. It takes a full minute to loop in the SMS version, but only 50 seconds in the GG version.

I tested the GG version in 3 other emulators: Kega Fusion, Mednafen and Genesis Plus GX (via Retroarch). In all of them the audio plays at the same rate as the SMS counterpart.
_____________________________

Aside from Master of Darkness / In the Wake of Vampire which is bugged in all versions, all other games used to work fine in 2.2.2.

**Comment by alyosha-tas** [comment] 2018-09-13 22:43
Did you try the dev build?

Apparently I messed something up in 2.3 that then maybe got fixed in Dev. I don’t remember though .

**Comment by synnae** [comment] 2018-09-13 22:46
Yes. Those were all tested with the 2018-09-13 dev build.

**Comment by alyosha-tas** [comment] 2018-09-13 23:17
Do you think you can do a bisect of where the games stopped working? I can’t really check myself anymore but if I know where things got broken it should be easy to deduce the fix .

**Comment by synnae** [comment] 2018-09-13 23:38
Sorry, not sure how I'd do that.

May I ask why can't you check yourself anymore?

**Comment by alyosha-tas** [comment] 2018-09-14 00:17
I can still help with things like home brew, so if you find any examples like that I can definitely take a look at it.

**Comment by Asnivor** [comment] 2018-09-14 05:56
This mostly looks to have happened at 2.3.0 release, so I guess Z80 changes must be the cause?

The big one that stands out in my mind as having potential for a knock on effect is changing of interrupt response time:

https://github.com/TASVideos/BizHawk/commit/3ce546b774d27d32db733e6f86b9c4e3717bf927

If anything is gonnna break stuff, I reckon it is that (although I don't know where to start diagnosing in  SMSHawk)

**Comment by Asnivor** [comment] 2018-09-14 10:33
ok, i've finished the first bisect (for Kujaku Ou). The offending commit is:

https://github.com/TASVideos/BizHawk/commit/9c06ac02a21b1aeb74f74ad7a5b5ccc02a7427b8

@alyosha-tas if you remember the Z80 before this was not setting flags **AT ALL** for IN operations. Clearly SMSHawk was built originally working around this.

Hopefully this helps. If you want to make any blind changes in a new branch I will be happy to test them for you. There is a good chance that fixing this for Kujaku Ou will also fix a bunch of other games (hopefully).

**Comment by Asnivor** [comment] 2018-09-14 11:34
OK, further bisecting has happened. The following games' issues are all caused by that same commit.

### 9c06ac0
* Argos no Juujiken (SMS) 
* Kujaku Ou (SMS)
* Double Target - Cynthia no Nemuri (SMS) 
* The Ninja (SMS) 
* Zillion (SMS)

**Comment by alyosha-tas** [comment] 2018-09-14 21:49
Thanks for the bisect that really makes it easier. 

Can you do some testing and see which flag is causing the issues? I would have to guess it is the zero flag but it would help to make sure.

I’ll look over the documentation and see if any registers have bits being set improperly.

Worst case scenario it’s timing related to reading vertical line counter, but let’s see

**Comment by Asnivor** [comment] 2018-09-18 08:08
Yup, looks like its FlagZ as you said.

https://github.com/TASVideos/BizHawk/commit/9c06ac02a21b1aeb74f74ad7a5b5ccc02a7427b8#diff-9db4fc073e99dcd14423ce534669b4ebR43

Commenting that line out stops the corruption. The documentation appears to suggest that the Zero flag should be set it the value is zero for IN r,(C)/IN F,(C)/INI/INIR,IND and INDR (as you currently have in place) so i'm guessing the issue is elsewhere?

It does however look like OUTI/OTIR/OUTD/OTDR should have the same flags affection as INI/INIR/IND/INDR (but the regular OUT instructions do not), but I don't see anything to this effect in OUT_Func. Not sure if this is likely to have an impact on the current issue though.

I'm looking here btw: http://www.z80.info/z80sflag.htm

**Comment by alyosha-tas** [comment] 2018-09-18 23:36
The out flags are accounted for in Out_OP_R so the out function itself does not need to set individual flags . 

At the moment I’m not really seeing anything wrong on the z80 end and certainly all the flag tests from the spectrum pass so I’m thinking the problem is elsewhere.

Can you post a trace log from a frame of one of the games that is glitchy ? Maybe post one of the same frame but with the zero flag not set so the difference should be obvious. That should make it clear what the fix needs to be. I hope.

**Comment by Asnivor** [comment] 2018-09-19 09:11
Ok, it took a little messing around in TAStudio to find the first frame where the IN zero flag setting makes a difference to the outputted graphics.

![image](https://user-images.githubusercontent.com/7911038/45742531-1692cf80-bbf2-11e8-8b53-9b93ccfd5551.png)
[Zillion (U) (Rev 1)_frame555_corrupted.log](https://github.com/TASVideos/BizHawk/files/2396246/Zillion.U.Rev.1._frame555_corrupted.log)


![image](https://user-images.githubusercontent.com/7911038/45742557-28747280-bbf2-11e8-970e-e5dcd9ff2e88.png)
[Zillion (U) (Rev 1)_frame555_working.log](https://github.com/TASVideos/BizHawk/files/2396257/Zillion.U.Rev.1._frame555_working.log)


You can see that the differences start on line 3987 (as a result of the IN at 3986):

![image](https://user-images.githubusercontent.com/7911038/45742634-5eb1f200-bbf2-11e8-9435-028e91613b72.png)

It looks like A is getting set to a different value based on the state of FlagZ, but I dont know/cant see why this would be the case at the moment...

**Comment by alyosha-tas** [comment] 2018-09-19 10:00
That’s the flag byte being set differently, it’s just not setting the Z flag as expected . Since the cycle counts are also the same, the problem probably lies further down. Maybe they diverge somewhere? That’s usually one of the things I look for.

**Comment by Asnivor** [comment] 2018-09-19 10:07
Yup. There is a JP NZ call here where it next diverges from a cycle-count POV:

![image](https://user-images.githubusercontent.com/7911038/45746724-cfa9d780-bbfb-11e8-9718-16d14139c59a.png)

Obviously this jumps based on the ZFlag so I guess this is where stuff starts to fall apart?

**Comment by alyosha-tas** [comment] 2018-09-19 10:52
Yup that’s what we’re looking for.

So either reading from port BE is not supposed to be zero there or the zero flag just doesn’t get set for some reason .

Port BE is just reading from VRAM apparently.

**Comment by alyosha-tas** [comment] 2018-09-19 10:58
The z80 data sheet says that flags for In A,n are not effected. So, I guess that solves that.

**Comment by alyosha-tas** [comment] 2018-09-19 11:09
IN A, (c) still needs the flags to be there.

So we need to split them up somehow.

All I have right now is my cell phone so I can’t really throw anything together. Probably the easiest thing to do is just make another function for IN A,n to call.

**Comment by Asnivor** [comment] 2018-09-19 11:10
Ok, i'll take a look

**Comment by Asnivor** [comment] 2018-09-19 22:07
Moved Master of Darkness / In the Wake of Vampire to separate issue - #1332 

Everything else here is now fixed in the master branch

**Closed by Asnivor** 2018-09-19 22:07 UTC
Labels: Core-SMSHawk, bug
