### ISSUE TITLE
Bizhawk movies can load save states from a different input movie

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#2644] opened 2021-02-25 03:16 UTC
I recorded a short input movie for Legend of Mana on Octoshock core, then deleted it. Then I recorded a short input movie for the same game under the same file name, and Bizhawk could load save states from the previous movie into the new one, although save states made much later (maybe with a much bigger frame difference) would crash the emulator as usual.

**Comment by YoshiRulz** [comment] 2021-02-25 03:37
Duplicate of #2484.

**Closed by YoshiRulz** 2021-02-25 03:37 UTC
