### ISSUE TITLE
Multi disk bundler good iso recognise

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1669] opened 2019-09-13 21:59 UTC
Is you load a multi disk iso normal the emu show as good iso the green mark and you merge using multi disk bundler they show warning unknow rom or show as ? Mario block

**Comment by YoshiRulz** [comment] 2019-09-14 05:54
Duplicate of #245.

**Closed by YoshiRulz** 2019-09-14 05:54 UTC
