### ISSUE TITLE
GBA BIOS skip

### ISSUE THREAD

**Issue by Weirwindle** [TASVideos/BizHawk#1540] opened 2019-04-15 06:12 UTC
Using the mgba core BIOS is **NOT** skipped (when BIOS skip is set to true).
BIOS is skipped, however,  on the VBA-next core.

**Comment by sornerol** [comment] 2019-05-14 01:51
This seems to be a duplicate of #1432, which has since been fixed.

**Comment by YoshiRulz** [comment] 2019-05-14 02:45
Earlier issue wasn't labelled so I missed it.

**Comment by Weirwindle** [comment] 2019-05-15 01:22
sornerol- "This seems to be a duplicate of #1432, which has since been fixed."
You did not read well enough. This is not a duplicate. Different core, same problem.
#1432 had a problem with the **VBA** core not skipping BIOS (which was fixed)
This post if for the **mGBA** core. It will not skip BIOS even when "Skip BIOS" is set to true, even in newer development versions.
This problem is **NOT** fixed. Please reopen this Issue.

**Comment by sornerol** [comment] 2019-05-15 02:49
Weirwindle, I'm afraid you're mistaken. There is a video attached to 1432 to illustrate the bug, and it is using the mGBA core.

I did test using the latest development build of BizHawk, and the BIOS skip functionality works properly on both mGBA and VBA-Next.

**Comment by RetroEdit** [comment] 2020-08-16 01:42
sornerol appears to be correct, and the video does indeed show mGBA. In my own testing, 2.3.1 has problems with bios skip for mGBA, but 2.3.2 fixes them. VBA-Next did not seem to have any problems.

This issue has been open for over a year with no response from @Weirwindle. Hence:

Duplicate of #1432.

**Closed by RetroEdit** 2020-08-16 01:42 UTC
Labels: Core: mGBA
