### ISSUE TITLE
Saving issues with Majora's Mask

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#397] opened 2015-06-22 14:37 UTC
```
What steps will reproduce the problem?
1. refer to additional info section
2.
3.

What is the expected output? What do you see instead?
1) saving with ocarina on b should keep ocarina on B. Instead, sword is 
restored.
2) saving with 0th day (no ammo) and resetting should save the file in its 
current state. Instead, it restores the old owl save.

What version of the product are you using? On what operating system?
Bizhawk 1.9.1 on Win7

Please provide any additional information below.
what i wrote in #bizhawk:
[23:52] <keeta> ok basically 2 things with Majora's Mask, they might be related:
[23:52] <keeta> 1) when you get ocarina on B, then save with song of time, 
ocarina doesn't stay on your B button, though it should
[23:53] <keeta> 2) save at the hidden owl, play song of time with no ammo, and 
reset after saving. instead of making a new save, the old owl save is restored
[23:54] <keeta> hard to explain if you don't have knowledge of glitches but i 
think something is off with the way bizhawk does saving?
[23:57] <keeta> i could make a m64 to prove it, but it would be really lengthy 
since i think bizhawks m64 reader needs to start from power on
Email me if you need more info i guess

```

Original issue reported on code.google.com by `Kazta...@gmail.com` on 17 Feb 2015 at 5:17

**Comment by YoshiRulz** [comment] 2019-10-27 04:26
Closing this because it has never been reproduced on 1.x and has never been encountered on 2.x.

**Closed by YoshiRulz** 2019-10-27 04:26 UTC
Labels: Core-Mupen64Plus
