### ISSUE TITLE
Feature request add mednafen PCE cores.

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1215] opened 2018-06-11 12:51 UTC
I use bizhawk for everything except PCE. Every bizhawk build has problems with one rom or the other that I want so for this alone I run mednafen.

I was wondering if it would be possible to add the mednafen pce core?

Not replace the existing but have both?

**Comment by alyosha-tas** [comment] 2018-06-12 21:20
This is a duplicate of #960 

PCE is a known weakness of BizHawk, unfortunately.

**Closed by alyosha-tas** 2018-06-12 21:20 UTC
