### ISSUE TITLE
"Unable to compare two elements in table" bug and a feature request

### ISSUE THREAD

**Issue by phoenix1291** [TASVideos/BizHawk#904] opened 2017-07-05 19:33 UTC
As I said in Bug Report part of [tasvideos forum](http://tasvideos.org/forum/viewtopic.php?t=12519&postdays=0&postorder=asc&start=1525) (9th message) with Saturnus core (and with mega-cd too) load movie result in a error "Unable to compare two elements in table"

"Bizhawk 2.0.0 rev 3d443b3e2 
Saturnus core 

Load Guardian Heroes (USA) (Hawked) 
(SHA1 CCD 27B6C8310B3DCF3E02F12E47C2F94AB6A7C3F4AC) 
(SHA1 IMG 35F320BBEFB9657790CF12E182468697349EAC60) 
Record movie 
Stop movie 
Load movie "

[Full error message](https://pastebin.com/kfCeJXTP)

I'am not the only one affect by this bug, and my PC was re-formatted this weekend
So, I will request a feature, by check box in config->customize perhaps, when a movie is drag and drop into BizHawk, is it possible to have a prompt with "stop movie at frame XX" or at least "stop movie at end"?

**Comment by zeromus** [comment] 2017-07-05 22:51
works for me.

do it again but delete all your existing movies, and name the new movie poops.bk2

We are not going to add an option called "don't do so much of whatever doesn't work". We are going to fix whatever doesn't work.

**Comment by phoenix1291** [comment] 2017-07-05 22:56
So, you think it's just a problem of number of character of the file's name?

**Comment by zeromus** [comment] 2017-07-05 22:58
No. If so I would have told you to create 1289312912312903 files named у́рйскиязкы́

**Comment by YoshiRulz** [comment] 2019-04-09 08:34
Closing as this appears to be a heisenbug, I couldn't find a tracelog containing both "BizHawk" and "System.Collections.Generic.KeyNotFoundException".

@phoenix1291 If you can reproduce this issue but the suggested fix didn't work, comment with more detail or join IRC.

**Closed by YoshiRulz** 2019-04-09 08:34 UTC
Labels: App-EmuHawk, bug
