### ISSUE TITLE
Feature Request - Controller Vibration

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2039] opened 2020-05-24 02:31 UTC
I've got an X-Box360 controller. It would be really cool if games that had vibration events triggered the vibration on the controller.

**Comment by YoshiRulz** [comment] 2020-05-24 03:42
Duplicate of #1756 (WIP [here](https://github.com/TASVideos/BizHawk/tree/get-ready-to-rumble)).

**Closed by YoshiRulz** 2020-05-24 03:42 UTC
Labels: App: EmuHawk, Enhancement
