### ISSUE TITLE
[PSX] [2.6] PAL Games Makes the Audio High-Pitched

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#2608] opened 2021-02-04 23:07 UTC
I've tested this with a few games that runs in the PAL Format.
I've also tested this using 2 different PAL Bios and with that, im guessing it will be the same for any other.

How to reproduce:
1. Pick any PSX Pal game.
2. Sound Config doesn't matter.
3. Audio is High-Pitched.

Semi-Fix:
(Without closing the BizHawk Emulator)
1. After picking a PSX Pal game, go to the Sound Config.
2. Change the Output Method to anything else and press OK.
(After that it's safe to re-change back to your current Output Method.)
3. Audio is No longer High-Pitched, as long if you keep the emulator running, the semi-fix will keep staying.

If you close the emulator, you will have to repeat the Semi-Fix steps.

**Comment by YoshiRulz** [comment] 2021-02-04 23:25
Possibly duplicate of #2580? Please try a [dev build](https://github.com/TASVideos/BizHawk#development-builds).

**Comment by Spikestuff** [comment] 2021-02-05 01:55
Assuming you're playing casually:
Config > Speed/Skip > Audio Throttle
Is the actual temporary solution... until you're dumping video.

**Comment by nattthebear** [comment] 2021-02-06 00:04
Given the repro instructions.  I'm positive this is #2580.  Dev build and audio throttle are the workarounds as already stated.

**Closed by nattthebear** 2021-02-06 00:04 UTC
Labels: App: EmuHawk, Core: Octoshock, Repro: Affects 2.6
