### ISSUE TITLE
Crashes when changing volume on laptop

### ISSUE THREAD

**Issue by Snodeca** [TASVideos/BizHawk#2459] opened 2020-10-20 14:53 UTC
### Summary
When you try to change your system volume on Windows on a laptop (Fn+F1 to mute, Fn+F2 to decrease and Fn+F3 to increase, in my case), Bizhawk crashes. This does not happen when I connect an external keybard through USB and use the keys to change volume with it.
Possible addition: on my laptop, by default, the F1-F12 keys would perform the action assigned to it (such as F11 decreasing brightness) without the need to use Fn, and holding the Fn key while pressing F11 would make the browser full screen. I myself changed this in the BIOS settings of my computer to be reversed, so I have to hold the Fn key to lower the brightness and I simply press F11 to go full screen. This may help reproduce it. It is 100% reproducable for me.

### Repro
1. Open Bizhawk
2. On a laptop, change volume using your Fn+volume keys.
 

This happens on Bizhawk version 2.5.2 but does not seem to happen on Bizhawk version 2.4 or earlier.

**Comment by nattthebear** [comment] 2020-10-20 15:01
Most likely a duplicate of or related to https://github.com/TASVideos/BizHawk/issues/2458

**Comment by YoshiRulz** [comment] 2020-10-20 22:48
Weird that it *doesn't* affect 2.4 or earlier, as OpenTK was only the default between 2.4.1 and 2.5.1 inclusive.

**Closed** 2020-10-21 02:50 UTC
Labels: App: EmuHawk, Repro: Affects 2.5.2
