### ISSUE TITLE
Can't Change Save Type

### ISSUE THREAD

**Issue by Octotroph** [TASVideos/BizHawk#1327] opened 2018-09-17 00:18 UTC
I've been Googling this problem, but nobody seems to have encountered it while using BizHawk.

It may just be a bit of naivete on my part, but when playing Pokemon AshGray (I've not tried it with other GBA games yet because I don't want to lose progress) I get "Save error. Please exchange the backup memory." when I try to save. The common solution is to change the save type to "Flash 128k" or something, but I can't find an option to do this in BizHawk. Am I missing something? Is this an oversight? Do I simply not have to worry about saving?

I'm using VBA-Next. I don't know how to make my savestates compatible with mGBA, and that's what I've been using to save, so if the fix is mGBA-only I'll also need to know how to save my states.

**Comment by hegyak** [comment] 2018-09-17 20:51
Check this Issue:
https://github.com/TASVideos/BizHawk/issues/700

It should help you figure out what you need to do to get BizHawk to handle your ROM properly.

**Comment by Octotroph** [comment] 2018-09-18 01:01
I don't see how that helps.
A) I'm using VBA-Next, not mGBA. Unless I can convert my savestates to mGBA format, that fact won't be changing any time soon.
B) The game runs fine, except when I'm trying to save. No time issues that I know of.
Perhaps, since it's designed for speedrunning, BizHawk's save functionality has been a tad neglected (which is perfectly understandable). So far I'm fine with using savestates to save my progress, but at some point I'm going to forget that and have to start over.

**Comment by NarryG** [comment] 2018-09-18 01:03
The issue is relevant as it's about gamedb. You'll need to configure Bizhawk to recognize the save type since it's a romhack and Bizhawk wants to be 100% sure it has the correct save format. The issue is about mGBA using the wrong gamedb, but editing the userdb to add this romhack still applies here.

**Comment by zeromus** [comment] 2018-11-02 02:55
cool workaround probably works. closing.

**Closed by zeromus** 2018-11-02 02:55 UTC
