### ISSUE TITLE
Pocket Monster 2 on Sega Genesis crashes BizHawk after title screen.

### ISSUE THREAD

**Issue by noddy360** [TASVideos/BizHawk#1972] opened 2020-05-02 23:21 UTC
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
The bootleg Genesis game, Pocket Monster 2 crashes BizHawk. The game boots and shows the title screen, but after pressing Start on the title screen the emulator crashes. I'm using BizHawk 2.4.1.
This didn't happen on earlier 32bit versions of BizHawk (like 1.13.2), as the game runs fine and its playable on that version.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load Pocket Monsters 2 (Unl) [!].bin on BizHawk
2. Press Start on the Title Screen.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.4.1; Win10 Pro; Intel
- BizHawk 1.13.2; Win10 Pro; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by nattthebear** [comment] 2020-05-05 18:41
Easily reproduced it here.  This will affect and likely break any title using `mapper_32k_w`.  According to documentation in the source code, that includes

>Custom ROM Bankswitch used in Soul Edge VS Samurai Spirits, Top Fighter, Mulan, Pocket Monsters II, Lion King 3, Super King Kong 99, Pokemon Stadium


It's not easily fixed.  I'll think on it a bit.

**Comment by nattthebear** [comment] 2020-05-05 19:03
I'm going to write how I tracked this down, in case anyone ever wants to get started with waterbox.

First of all, we need to rebuild gpgx with symbols:

```diff
diff --git a/waterbox/gpgx/Makefile b/waterbox/gpgx/Makefile
index ba9cad8d00af0bbb1acb821b791a9df40cbc35c4..2ce1f509275b07321c8f2e26f1eedfee19b440ce 100644
--- a/waterbox/gpgx/Makefile
+++ b/waterbox/gpgx/Makefile
@@ -6,7 +6,7 @@ CCFLAGS:=-Icore -Iutil -Icore/m68k -Icore/z80 -Icore/input_hw \
 	-Wall -Werror=pointer-to-int-cast -Werror=int-to-pointer-cast -Werror=implicit-function-declaration \
 	-std=c99 -fomit-frame-pointer -fvisibility=hidden \
 	-DLSB_FIRST -DUSE_32BPP_RENDERING -DINLINE=static\ __inline__ \
-	-O3 -flto
+	-O0 -g
 
 TARGET = gpgx.wbx
 
@@ -31,7 +31,8 @@ $(TARGET).in: $(OBJS)
 	@$(CC) -o $@ $(LDFLAGS) $(CCFLAGS) $(OBJS) ../emulibc/libemuhost.so
 
 $(TARGET): $(TARGET).in
-	strip $< -o $@ -R /4 -R /14 -R /29 -R /41 -R /55 -R /67 -R /78 -R /89 -R /104
+	cp $< $@
+#	strip $< -o $@ -R /4 -R /14 -R /29 -R /41 -R /55 -R /67 -R /78 -R /89 -R /104
 
 clean:
 	rm -rf $(OBJ_DIR)
```

Delete `gpgx.wbx` and replace it with that bad boy.

Then we need to start bizhawk, and then start and attach gdb.  The gdb commands:

GDB is a dumbass and gets confused with .net processes
```
set arch i386:x86-64:intel
```

GDB needs to know where symbols are.  You can copy these command lines right out of Bizhawk's message log.
```
add-sym gpgx.wbx 3775276257280 -s .data 3775277178880 -s .bss 3775278698496
add-sym libc.so 3775298277376 -s .data 3775298908160 -s .bss 3775299289088
```

Then let gdb continue, and hit the crash.  You'll have everything you need:
```
(gdb) bt
#0  0x0000036f0150107e in memcpy ()
#1  0x0000036f0000957a in mapper_32k_w (data=1) at core/cart_hw/md_cart.c:1486
#2  0x0000036f00009a36 in custom_regs_w (address=7798903, data=1)
    at core/cart_hw/md_cart.c:1643
#3  0x0000036f00021806 in m68ki_write_8_fc (address=7798903, fc=5, value=1)
    at core/m68k/m68kcpu.h:936
#4  0x0000036f00042fc4 in m68k_op_move_8_di_i () at core/m68k/m68kops.h:11216
#5  0x0000036f00067981 in m68k_run (cycles=629280) at core/m68k/m68kcpu.c:357
#6  0x0000036f000bff0d in system_frame_gen (do_skip=0) at core/system.c:519
#7  0x0000036f000013d7 in gpgx_advance () at cinterface/cinterface.c:182
#8  0x000007fe8bd05bf7 in ?? ()
```

Here, `0x000007...` is back into managed code.  If a module shows up in the `0x000036...` range and you don't know what it is, look in the bizhawk log -- you might need to add symbols for something else, or recompile something else with symbols enabled.


With that knowledge, we can look back in the code and the problem is clear:  `mapper_32k_w` implements some bankswitching by `memcpy()`ing parts of the rom on top of itself, but that segfaults because that space isn't tracked by savestates and so is set as readonly.

**Comment by nattthebear** [comment] 2020-05-05 20:07
@noddy360 Can you give me the exact hash from rominfo of your rom that works on 1.x?

**Comment by noddy360** [comment] 2020-05-05 22:06
Lets see here, um...
(`MD5: 6A17B0713F1FA41E16C626DE408B91D4, SHA1: DAE100DFAEE1B5B7816731CB2F43BCDA3DA273B7, CRC32: 30F7031F`)
Is this what you're talking about?

**Comment by nattthebear** [comment] 2020-05-05 22:25
Yes, thank you.  Still looking into this one.

**Comment by nattthebear** [comment] 2020-05-06 13:40
Fixed in master

**Closed by nattthebear** 2020-05-06 13:40 UTC
Labels: Core: Genplus-gx, Homebrew, Repro: Affects 2.4.1
