### ISSUE TITLE
When I press the Numlock key, Bizhawk crashes instantly

### ISSUE THREAD

**Issue by brskiiii** [TASVideos/BizHawk#2851] opened 2021-07-13 11:56 UTC
Running on Windows 10. 

I really need numlock to work for other purposes while running this emulator. :(

**Comment by brskiiii** [comment] 2021-07-14 02:48
Oh I had downloaded the newest one before, but was accidentally using the 2.4 that I had in a different directory. I think it seemed to solve the issue.

How do I properly upgrade without losing all my settings and stuff? Do I just replace the exe's?

**Comment by zeromus** [comment] 2021-07-14 02:54
dearchive to a new directory
copy config.ini from old bizhawk to new bizhawk
copy all subdirectories EXCEPT FOR DLL from old bizhawk to new bizhawk

**Comment by YoshiRulz** [comment] 2021-07-14 08:55
Duplicate of #2389, fixed in 2.6 and later releases.

**Closed by YoshiRulz** 2021-07-14 08:55 UTC
Labels: App: EmuHawk
